/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package org.softwareforce.iotvm.shared.event;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class QualityPropertiesIBO extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5836716999325785414L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"QualityPropertiesIBO\",\"namespace\":\"org.softwareforce.iotvm.shared.event\",\"fields\":[{\"name\":\"metrics\",\"type\":{\"type\":\"map\",\"values\":[\"null\",\"double\"],\"avro.java.string\":\"String\"}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<QualityPropertiesIBO> ENCODER =
      new BinaryMessageEncoder<QualityPropertiesIBO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<QualityPropertiesIBO> DECODER =
      new BinaryMessageDecoder<QualityPropertiesIBO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<QualityPropertiesIBO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<QualityPropertiesIBO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<QualityPropertiesIBO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<QualityPropertiesIBO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this QualityPropertiesIBO to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a QualityPropertiesIBO from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a QualityPropertiesIBO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static QualityPropertiesIBO fromByteBuffer(java.nio.ByteBuffer b)
      throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.Map<java.lang.String, java.lang.Double> metrics;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public QualityPropertiesIBO() {}

  /**
   * All-args constructor.
   *
   * @param metrics The new value for metrics
   */
  public QualityPropertiesIBO(java.util.Map<java.lang.String, java.lang.Double> metrics) {
    this.metrics = metrics;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return metrics;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        metrics = (java.util.Map<java.lang.String, java.lang.Double>) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'metrics' field.
   *
   * @return The value of the 'metrics' field.
   */
  public java.util.Map<java.lang.String, java.lang.Double> getMetrics() {
    return metrics;
  }

  /**
   * Sets the value of the 'metrics' field.
   *
   * @param value the value to set.
   */
  public void setMetrics(java.util.Map<java.lang.String, java.lang.Double> value) {
    this.metrics = value;
  }

  /**
   * Creates a new QualityPropertiesIBO RecordBuilder.
   *
   * @return A new QualityPropertiesIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder newBuilder() {
    return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder();
  }

  /**
   * Creates a new QualityPropertiesIBO RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new QualityPropertiesIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder newBuilder(
      org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder other) {
    if (other == null) {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder();
    } else {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder(other);
    }
  }

  /**
   * Creates a new QualityPropertiesIBO RecordBuilder by copying an existing QualityPropertiesIBO
   * instance.
   *
   * @param other The existing instance to copy.
   * @return A new QualityPropertiesIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder newBuilder(
      org.softwareforce.iotvm.shared.event.QualityPropertiesIBO other) {
    if (other == null) {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder();
    } else {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder(other);
    }
  }

  /** RecordBuilder for QualityPropertiesIBO instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<QualityPropertiesIBO>
      implements org.apache.avro.data.RecordBuilder<QualityPropertiesIBO> {

    private java.util.Map<java.lang.String, java.lang.Double> metrics;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.metrics)) {
        this.metrics = data().deepCopy(fields()[0].schema(), other.metrics);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing QualityPropertiesIBO instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(org.softwareforce.iotvm.shared.event.QualityPropertiesIBO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.metrics)) {
        this.metrics = data().deepCopy(fields()[0].schema(), other.metrics);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Gets the value of the 'metrics' field.
     *
     * @return The value.
     */
    public java.util.Map<java.lang.String, java.lang.Double> getMetrics() {
      return metrics;
    }

    /**
     * Sets the value of the 'metrics' field.
     *
     * @param value The value of 'metrics'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder setMetrics(
        java.util.Map<java.lang.String, java.lang.Double> value) {
      validate(fields()[0], value);
      this.metrics = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'metrics' field has been set.
     *
     * @return True if the 'metrics' field has been set, false otherwise.
     */
    public boolean hasMetrics() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'metrics' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder clearMetrics() {
      metrics = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public QualityPropertiesIBO build() {
      try {
        QualityPropertiesIBO record = new QualityPropertiesIBO();
        record.metrics =
            fieldSetFlags()[0]
                ? this.metrics
                : (java.util.Map<java.lang.String, java.lang.Double>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<QualityPropertiesIBO> WRITER$ =
      (org.apache.avro.io.DatumWriter<QualityPropertiesIBO>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<QualityPropertiesIBO> READER$ =
      (org.apache.avro.io.DatumReader<QualityPropertiesIBO>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    long size0 = this.metrics.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Double> e0 : this.metrics.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.Double v0 = e0.getValue();
      if (v0 == null) {
        out.writeIndex(0);
        out.writeNull();
      } else {
        out.writeIndex(1);
        out.writeDouble(v0);
      }
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException(
          "Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readMapStart();
      java.util.Map<java.lang.String, java.lang.Double> m0 =
          this.metrics; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.String, java.lang.Double>((int) size0);
        this.metrics = m0;
      } else m0.clear();
      for (; 0 < size0; size0 = in.mapNext()) {
        for (; size0 != 0; size0--) {
          java.lang.String k0 = null;
          k0 = in.readString();
          java.lang.Double v0 = null;
          if (in.readIndex() != 1) {
            in.readNull();
            v0 = null;
          } else {
            v0 = in.readDouble();
          }
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            long size0 = in.readMapStart();
            java.util.Map<java.lang.String, java.lang.Double> m0 =
                this.metrics; // Need fresh name due to limitation of macro system
            if (m0 == null) {
              m0 = new java.util.HashMap<java.lang.String, java.lang.Double>((int) size0);
              this.metrics = m0;
            } else m0.clear();
            for (; 0 < size0; size0 = in.mapNext()) {
              for (; size0 != 0; size0--) {
                java.lang.String k0 = null;
                k0 = in.readString();
                java.lang.Double v0 = null;
                if (in.readIndex() != 1) {
                  in.readNull();
                  v0 = null;
                } else {
                  v0 = in.readDouble();
                }
                m0.put(k0, v0);
              }
            }
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
