/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * <p>DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.softwareforce.iotvm.shared.extensions.fabrication_backcasting.spec;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(
    value = "Autogenerated by Thrift Compiler (0.18.1)",
    date = "2023-09-02")
public class BackcastScope
    implements org.apache.thrift.TBase<BackcastScope, BackcastScope._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<BackcastScope> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
      new org.apache.thrift.protocol.TStruct("BackcastScope");

  private static final org.apache.thrift.protocol.TField PHYSICAL_QUANTITY_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "physicalQuantity", org.apache.thrift.protocol.TType.STRING, (short) 1);
  private static final org.apache.thrift.protocol.TField SENSOR_ID_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "sensorId", org.apache.thrift.protocol.TType.STRING, (short) 2);
  private static final org.apache.thrift.protocol.TField TOPIC_NAME_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "topicName", org.apache.thrift.protocol.TType.STRING, (short) 3);
  private static final org.apache.thrift.protocol.TField FREQUENCY_IN_SECONDS_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "frequencyInSeconds", org.apache.thrift.protocol.TType.I64, (short) 4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
      new BackcastScopeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
      new BackcastScopeTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String physicalQuantity; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String sensorId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String topicName; // required
  public long frequencyInSeconds; // required

  /**
   * The set of fields this struct contains, along with convenience methods for finding and
   * manipulating them.
   */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PHYSICAL_QUANTITY((short) 1, "physicalQuantity"),
    SENSOR_ID((short) 2, "sensorId"),
    TOPIC_NAME((short) 3, "topicName"),
    FREQUENCY_IN_SECONDS((short) 4, "frequencyInSeconds");

    private static final java.util.Map<java.lang.String, _Fields> byName =
        new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /** Find the _Fields constant that matches fieldId, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch (fieldId) {
        case 1: // PHYSICAL_QUANTITY
          return PHYSICAL_QUANTITY;
        case 2: // SENSOR_ID
          return SENSOR_ID;
        case 3: // TOPIC_NAME
          return TOPIC_NAME;
        case 4: // FREQUENCY_IN_SECONDS
          return FREQUENCY_IN_SECONDS;
        default:
          return null;
      }
    }

    /** Find the _Fields constant that matches fieldId, throwing an exception if it is not found. */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null)
        throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /** Find the _Fields constant that matches name, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FREQUENCYINSECONDS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
        new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(
        _Fields.PHYSICAL_QUANTITY,
        new org.apache.thrift.meta_data.FieldMetaData(
            "physicalQuantity",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(
        _Fields.SENSOR_ID,
        new org.apache.thrift.meta_data.FieldMetaData(
            "sensorId",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(
        _Fields.TOPIC_NAME,
        new org.apache.thrift.meta_data.FieldMetaData(
            "topicName",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(
        _Fields.FREQUENCY_IN_SECONDS,
        new org.apache.thrift.meta_data.FieldMetaData(
            "frequencyInSeconds",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
        BackcastScope.class, metaDataMap);
  }

  public BackcastScope() {}

  public BackcastScope(
      java.lang.String physicalQuantity,
      java.lang.String sensorId,
      java.lang.String topicName,
      long frequencyInSeconds) {
    this();
    this.physicalQuantity = physicalQuantity;
    this.sensorId = sensorId;
    this.topicName = topicName;
    this.frequencyInSeconds = frequencyInSeconds;
    setFrequencyInSecondsIsSet(true);
  }

  /** Performs a deep copy on <i>other</i>. */
  public BackcastScope(BackcastScope other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetPhysicalQuantity()) {
      this.physicalQuantity = other.physicalQuantity;
    }
    if (other.isSetSensorId()) {
      this.sensorId = other.sensorId;
    }
    if (other.isSetTopicName()) {
      this.topicName = other.topicName;
    }
    this.frequencyInSeconds = other.frequencyInSeconds;
  }

  @Override
  public BackcastScope deepCopy() {
    return new BackcastScope(this);
  }

  @Override
  public void clear() {
    this.physicalQuantity = null;
    this.sensorId = null;
    this.topicName = null;
    setFrequencyInSecondsIsSet(false);
    this.frequencyInSeconds = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPhysicalQuantity() {
    return this.physicalQuantity;
  }

  public BackcastScope setPhysicalQuantity(
      @org.apache.thrift.annotation.Nullable java.lang.String physicalQuantity) {
    this.physicalQuantity = physicalQuantity;
    return this;
  }

  public void unsetPhysicalQuantity() {
    this.physicalQuantity = null;
  }

  /**
   * Returns true if field physicalQuantity is set (has been assigned a value) and false otherwise
   */
  public boolean isSetPhysicalQuantity() {
    return this.physicalQuantity != null;
  }

  public void setPhysicalQuantityIsSet(boolean value) {
    if (!value) {
      this.physicalQuantity = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSensorId() {
    return this.sensorId;
  }

  public BackcastScope setSensorId(
      @org.apache.thrift.annotation.Nullable java.lang.String sensorId) {
    this.sensorId = sensorId;
    return this;
  }

  public void unsetSensorId() {
    this.sensorId = null;
  }

  /** Returns true if field sensorId is set (has been assigned a value) and false otherwise */
  public boolean isSetSensorId() {
    return this.sensorId != null;
  }

  public void setSensorIdIsSet(boolean value) {
    if (!value) {
      this.sensorId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTopicName() {
    return this.topicName;
  }

  public BackcastScope setTopicName(
      @org.apache.thrift.annotation.Nullable java.lang.String topicName) {
    this.topicName = topicName;
    return this;
  }

  public void unsetTopicName() {
    this.topicName = null;
  }

  /** Returns true if field topicName is set (has been assigned a value) and false otherwise */
  public boolean isSetTopicName() {
    return this.topicName != null;
  }

  public void setTopicNameIsSet(boolean value) {
    if (!value) {
      this.topicName = null;
    }
  }

  public long getFrequencyInSeconds() {
    return this.frequencyInSeconds;
  }

  public BackcastScope setFrequencyInSeconds(long frequencyInSeconds) {
    this.frequencyInSeconds = frequencyInSeconds;
    setFrequencyInSecondsIsSet(true);
    return this;
  }

  public void unsetFrequencyInSeconds() {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FREQUENCYINSECONDS_ISSET_ID);
  }

  /**
   * Returns true if field frequencyInSeconds is set (has been assigned a value) and false otherwise
   */
  public boolean isSetFrequencyInSeconds() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FREQUENCYINSECONDS_ISSET_ID);
  }

  public void setFrequencyInSecondsIsSet(boolean value) {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.setBit(
            __isset_bitfield, __FREQUENCYINSECONDS_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(
      _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
      case PHYSICAL_QUANTITY:
        if (value == null) {
          unsetPhysicalQuantity();
        } else {
          setPhysicalQuantity((java.lang.String) value);
        }
        break;

      case SENSOR_ID:
        if (value == null) {
          unsetSensorId();
        } else {
          setSensorId((java.lang.String) value);
        }
        break;

      case TOPIC_NAME:
        if (value == null) {
          unsetTopicName();
        } else {
          setTopicName((java.lang.String) value);
        }
        break;

      case FREQUENCY_IN_SECONDS:
        if (value == null) {
          unsetFrequencyInSeconds();
        } else {
          setFrequencyInSeconds((java.lang.Long) value);
        }
        break;
    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
      case PHYSICAL_QUANTITY:
        return getPhysicalQuantity();

      case SENSOR_ID:
        return getSensorId();

      case TOPIC_NAME:
        return getTopicName();

      case FREQUENCY_IN_SECONDS:
        return getFrequencyInSeconds();
    }
    throw new java.lang.IllegalStateException();
  }

  /**
   * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
   * otherwise
   */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
      case PHYSICAL_QUANTITY:
        return isSetPhysicalQuantity();
      case SENSOR_ID:
        return isSetSensorId();
      case TOPIC_NAME:
        return isSetTopicName();
      case FREQUENCY_IN_SECONDS:
        return isSetFrequencyInSeconds();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof BackcastScope) return this.equals((BackcastScope) that);
    return false;
  }

  public boolean equals(BackcastScope that) {
    if (that == null) return false;
    if (this == that) return true;

    boolean this_present_physicalQuantity = true && this.isSetPhysicalQuantity();
    boolean that_present_physicalQuantity = true && that.isSetPhysicalQuantity();
    if (this_present_physicalQuantity || that_present_physicalQuantity) {
      if (!(this_present_physicalQuantity && that_present_physicalQuantity)) return false;
      if (!this.physicalQuantity.equals(that.physicalQuantity)) return false;
    }

    boolean this_present_sensorId = true && this.isSetSensorId();
    boolean that_present_sensorId = true && that.isSetSensorId();
    if (this_present_sensorId || that_present_sensorId) {
      if (!(this_present_sensorId && that_present_sensorId)) return false;
      if (!this.sensorId.equals(that.sensorId)) return false;
    }

    boolean this_present_topicName = true && this.isSetTopicName();
    boolean that_present_topicName = true && that.isSetTopicName();
    if (this_present_topicName || that_present_topicName) {
      if (!(this_present_topicName && that_present_topicName)) return false;
      if (!this.topicName.equals(that.topicName)) return false;
    }

    boolean this_present_frequencyInSeconds = true;
    boolean that_present_frequencyInSeconds = true;
    if (this_present_frequencyInSeconds || that_present_frequencyInSeconds) {
      if (!(this_present_frequencyInSeconds && that_present_frequencyInSeconds)) return false;
      if (this.frequencyInSeconds != that.frequencyInSeconds) return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPhysicalQuantity()) ? 131071 : 524287);
    if (isSetPhysicalQuantity()) hashCode = hashCode * 8191 + physicalQuantity.hashCode();

    hashCode = hashCode * 8191 + ((isSetSensorId()) ? 131071 : 524287);
    if (isSetSensorId()) hashCode = hashCode * 8191 + sensorId.hashCode();

    hashCode = hashCode * 8191 + ((isSetTopicName()) ? 131071 : 524287);
    if (isSetTopicName()) hashCode = hashCode * 8191 + topicName.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(frequencyInSeconds);

    return hashCode;
  }

  @Override
  public int compareTo(BackcastScope other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison =
        java.lang.Boolean.compare(isSetPhysicalQuantity(), other.isSetPhysicalQuantity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPhysicalQuantity()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(this.physicalQuantity, other.physicalQuantity);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSensorId(), other.isSetSensorId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSensorId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sensorId, other.sensorId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTopicName(), other.isSetTopicName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTopicName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.topicName, other.topicName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison =
        java.lang.Boolean.compare(isSetFrequencyInSeconds(), other.isSetFrequencyInSeconds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFrequencyInSeconds()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(
              this.frequencyInSeconds, other.frequencyInSeconds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot)
      throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BackcastScope(");
    boolean first = true;

    sb.append("physicalQuantity:");
    if (this.physicalQuantity == null) {
      sb.append("null");
    } else {
      sb.append(this.physicalQuantity);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sensorId:");
    if (this.sensorId == null) {
      sb.append("null");
    } else {
      sb.append(this.sensorId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("topicName:");
    if (this.topicName == null) {
      sb.append("null");
    } else {
      sb.append(this.topicName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("frequencyInSeconds:");
    sb.append(this.frequencyInSeconds);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in)
      throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and
      // doesn't call the default constructor.
      __isset_bitfield = 0;
      read(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BackcastScopeStandardSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public BackcastScopeStandardScheme getScheme() {
      return new BackcastScopeStandardScheme();
    }
  }

  private static class BackcastScopeStandardScheme
      extends org.apache.thrift.scheme.StandardScheme<BackcastScope> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, BackcastScope struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true) {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // PHYSICAL_QUANTITY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.physicalQuantity = iprot.readString();
              struct.setPhysicalQuantityIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SENSOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sensorId = iprot.readString();
              struct.setSensorIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TOPIC_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.topicName = iprot.readString();
              struct.setTopicNameIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FREQUENCY_IN_SECONDS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.frequencyInSeconds = iprot.readI64();
              struct.setFrequencyInSecondsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, BackcastScope struct)
        throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.physicalQuantity != null) {
        oprot.writeFieldBegin(PHYSICAL_QUANTITY_FIELD_DESC);
        oprot.writeString(struct.physicalQuantity);
        oprot.writeFieldEnd();
      }
      if (struct.sensorId != null) {
        oprot.writeFieldBegin(SENSOR_ID_FIELD_DESC);
        oprot.writeString(struct.sensorId);
        oprot.writeFieldEnd();
      }
      if (struct.topicName != null) {
        oprot.writeFieldBegin(TOPIC_NAME_FIELD_DESC);
        oprot.writeString(struct.topicName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FREQUENCY_IN_SECONDS_FIELD_DESC);
      oprot.writeI64(struct.frequencyInSeconds);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
  }

  private static class BackcastScopeTupleSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public BackcastScopeTupleScheme getScheme() {
      return new BackcastScopeTupleScheme();
    }
  }

  private static class BackcastScopeTupleScheme
      extends org.apache.thrift.scheme.TupleScheme<BackcastScope> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BackcastScope struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPhysicalQuantity()) {
        optionals.set(0);
      }
      if (struct.isSetSensorId()) {
        optionals.set(1);
      }
      if (struct.isSetTopicName()) {
        optionals.set(2);
      }
      if (struct.isSetFrequencyInSeconds()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetPhysicalQuantity()) {
        oprot.writeString(struct.physicalQuantity);
      }
      if (struct.isSetSensorId()) {
        oprot.writeString(struct.sensorId);
      }
      if (struct.isSetTopicName()) {
        oprot.writeString(struct.topicName);
      }
      if (struct.isSetFrequencyInSeconds()) {
        oprot.writeI64(struct.frequencyInSeconds);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BackcastScope struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.physicalQuantity = iprot.readString();
        struct.setPhysicalQuantityIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sensorId = iprot.readString();
        struct.setSensorIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.topicName = iprot.readString();
        struct.setTopicNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.frequencyInSeconds = iprot.readI64();
        struct.setFrequencyInSecondsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
      org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
            ? STANDARD_SCHEME_FACTORY
            : TUPLE_SCHEME_FACTORY)
        .getScheme();
  }
}
