/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * <p>DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.softwareforce.iotvm.shared.extensions.fabrication_backcasting.spec;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(
    value = "Autogenerated by Thrift Compiler (0.18.1)",
    date = "2023-09-02")
public class BackcastResponse
    implements org.apache.thrift.TBase<BackcastResponse, BackcastResponse._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<BackcastResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
      new org.apache.thrift.protocol.TStruct("BackcastResponse");

  private static final org.apache.thrift.protocol.TField VALUE_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "value", org.apache.thrift.protocol.TType.DOUBLE, (short) 1);
  private static final org.apache.thrift.protocol.TField START_TIMESTAMP_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "startTimestamp", org.apache.thrift.protocol.TType.I64, (short) 2);
  private static final org.apache.thrift.protocol.TField END_TIMESTAMP_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "endTimestamp", org.apache.thrift.protocol.TType.I64, (short) 3);
  private static final org.apache.thrift.protocol.TField METRICS_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "metrics", org.apache.thrift.protocol.TType.MAP, (short) 4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
      new BackcastResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
      new BackcastResponseTupleSchemeFactory();

  public double value; // required

  /**
   * UTC Timestamp in milliseconds representing the start of the time window in which the backcasted
   * value belongs.
   */
  public long startTimestamp; // required

  /**
   * UTC Timestamp in milliseconds representing the end of the time window in which the backcasted
   * value belongs.
   */
  public long endTimestamp; // required

  /**
   * Any metric regarding the model.
   *
   * <p>Some metrics refer to score functions or loss functions. Score functions: the bigger value
   * the better. Loss functions: the smaller value the better. Negative numbers may indicate bad
   * data fitting. Positive or negative inf may also indicate bad data fitting.
   */
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.Double>
      metrics; // required

  /**
   * The set of fields this struct contains, along with convenience methods for finding and
   * manipulating them.
   */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VALUE((short) 1, "value"),
    /**
     * UTC Timestamp in milliseconds representing the start of the time window in which the
     * backcasted value belongs.
     */
    START_TIMESTAMP((short) 2, "startTimestamp"),
    /**
     * UTC Timestamp in milliseconds representing the end of the time window in which the backcasted
     * value belongs.
     */
    END_TIMESTAMP((short) 3, "endTimestamp"),
    /**
     * Any metric regarding the model.
     *
     * <p>Some metrics refer to score functions or loss functions. Score functions: the bigger value
     * the better. Loss functions: the smaller value the better. Negative numbers may indicate bad
     * data fitting. Positive or negative inf may also indicate bad data fitting.
     */
    METRICS((short) 4, "metrics");

    private static final java.util.Map<java.lang.String, _Fields> byName =
        new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /** Find the _Fields constant that matches fieldId, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch (fieldId) {
        case 1: // VALUE
          return VALUE;
        case 2: // START_TIMESTAMP
          return START_TIMESTAMP;
        case 3: // END_TIMESTAMP
          return END_TIMESTAMP;
        case 4: // METRICS
          return METRICS;
        default:
          return null;
      }
    }

    /** Find the _Fields constant that matches fieldId, throwing an exception if it is not found. */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null)
        throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /** Find the _Fields constant that matches name, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VALUE_ISSET_ID = 0;
  private static final int __STARTTIMESTAMP_ISSET_ID = 1;
  private static final int __ENDTIMESTAMP_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
        new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(
        _Fields.VALUE,
        new org.apache.thrift.meta_data.FieldMetaData(
            "value",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(
        _Fields.START_TIMESTAMP,
        new org.apache.thrift.meta_data.FieldMetaData(
            "startTimestamp",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(
        _Fields.END_TIMESTAMP,
        new org.apache.thrift.meta_data.FieldMetaData(
            "endTimestamp",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(
        _Fields.METRICS,
        new org.apache.thrift.meta_data.FieldMetaData(
            "metrics",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.MapMetaData(
                org.apache.thrift.protocol.TType.MAP,
                new org.apache.thrift.meta_data.FieldValueMetaData(
                    org.apache.thrift.protocol.TType.STRING),
                new org.apache.thrift.meta_data.FieldValueMetaData(
                    org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
        BackcastResponse.class, metaDataMap);
  }

  public BackcastResponse() {}

  public BackcastResponse(
      double value,
      long startTimestamp,
      long endTimestamp,
      java.util.Map<java.lang.String, java.lang.Double> metrics) {
    this();
    this.value = value;
    setValueIsSet(true);
    this.startTimestamp = startTimestamp;
    setStartTimestampIsSet(true);
    this.endTimestamp = endTimestamp;
    setEndTimestampIsSet(true);
    this.metrics = metrics;
  }

  /** Performs a deep copy on <i>other</i>. */
  public BackcastResponse(BackcastResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.value = other.value;
    this.startTimestamp = other.startTimestamp;
    this.endTimestamp = other.endTimestamp;
    if (other.isSetMetrics()) {
      java.util.Map<java.lang.String, java.lang.Double> __this__metrics =
          new java.util.HashMap<java.lang.String, java.lang.Double>(other.metrics);
      this.metrics = __this__metrics;
    }
  }

  @Override
  public BackcastResponse deepCopy() {
    return new BackcastResponse(this);
  }

  @Override
  public void clear() {
    setValueIsSet(false);
    this.value = 0.0;
    setStartTimestampIsSet(false);
    this.startTimestamp = 0;
    setEndTimestampIsSet(false);
    this.endTimestamp = 0;
    this.metrics = null;
  }

  public double getValue() {
    return this.value;
  }

  public BackcastResponse setValue(double value) {
    this.value = value;
    setValueIsSet(true);
    return this;
  }

  public void unsetValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VALUE_ISSET_ID);
  }

  /** Returns true if field value is set (has been assigned a value) and false otherwise */
  public boolean isSetValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VALUE_ISSET_ID);
  }

  public void setValueIsSet(boolean value) {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VALUE_ISSET_ID, value);
  }

  /**
   * UTC Timestamp in milliseconds representing the start of the time window in which the backcasted
   * value belongs.
   */
  public long getStartTimestamp() {
    return this.startTimestamp;
  }

  /**
   * UTC Timestamp in milliseconds representing the start of the time window in which the backcasted
   * value belongs.
   */
  public BackcastResponse setStartTimestamp(long startTimestamp) {
    this.startTimestamp = startTimestamp;
    setStartTimestampIsSet(true);
    return this;
  }

  public void unsetStartTimestamp() {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTTIMESTAMP_ISSET_ID);
  }

  /** Returns true if field startTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTimestamp() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTTIMESTAMP_ISSET_ID);
  }

  public void setStartTimestampIsSet(boolean value) {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTTIMESTAMP_ISSET_ID, value);
  }

  /**
   * UTC Timestamp in milliseconds representing the end of the time window in which the backcasted
   * value belongs.
   */
  public long getEndTimestamp() {
    return this.endTimestamp;
  }

  /**
   * UTC Timestamp in milliseconds representing the end of the time window in which the backcasted
   * value belongs.
   */
  public BackcastResponse setEndTimestamp(long endTimestamp) {
    this.endTimestamp = endTimestamp;
    setEndTimestampIsSet(true);
    return this;
  }

  public void unsetEndTimestamp() {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDTIMESTAMP_ISSET_ID);
  }

  /** Returns true if field endTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetEndTimestamp() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDTIMESTAMP_ISSET_ID);
  }

  public void setEndTimestampIsSet(boolean value) {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDTIMESTAMP_ISSET_ID, value);
  }

  public int getMetricsSize() {
    return (this.metrics == null) ? 0 : this.metrics.size();
  }

  public void putToMetrics(java.lang.String key, double val) {
    if (this.metrics == null) {
      this.metrics = new java.util.HashMap<java.lang.String, java.lang.Double>();
    }
    this.metrics.put(key, val);
  }

  /**
   * Any metric regarding the model.
   *
   * <p>Some metrics refer to score functions or loss functions. Score functions: the bigger value
   * the better. Loss functions: the smaller value the better. Negative numbers may indicate bad
   * data fitting. Positive or negative inf may also indicate bad data fitting.
   */
  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String, java.lang.Double> getMetrics() {
    return this.metrics;
  }

  /**
   * Any metric regarding the model.
   *
   * <p>Some metrics refer to score functions or loss functions. Score functions: the bigger value
   * the better. Loss functions: the smaller value the better. Negative numbers may indicate bad
   * data fitting. Positive or negative inf may also indicate bad data fitting.
   */
  public BackcastResponse setMetrics(
      @org.apache.thrift.annotation.Nullable
          java.util.Map<java.lang.String, java.lang.Double> metrics) {
    this.metrics = metrics;
    return this;
  }

  public void unsetMetrics() {
    this.metrics = null;
  }

  /** Returns true if field metrics is set (has been assigned a value) and false otherwise */
  public boolean isSetMetrics() {
    return this.metrics != null;
  }

  public void setMetricsIsSet(boolean value) {
    if (!value) {
      this.metrics = null;
    }
  }

  @Override
  public void setFieldValue(
      _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
      case VALUE:
        if (value == null) {
          unsetValue();
        } else {
          setValue((java.lang.Double) value);
        }
        break;

      case START_TIMESTAMP:
        if (value == null) {
          unsetStartTimestamp();
        } else {
          setStartTimestamp((java.lang.Long) value);
        }
        break;

      case END_TIMESTAMP:
        if (value == null) {
          unsetEndTimestamp();
        } else {
          setEndTimestamp((java.lang.Long) value);
        }
        break;

      case METRICS:
        if (value == null) {
          unsetMetrics();
        } else {
          setMetrics((java.util.Map<java.lang.String, java.lang.Double>) value);
        }
        break;
    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
      case VALUE:
        return getValue();

      case START_TIMESTAMP:
        return getStartTimestamp();

      case END_TIMESTAMP:
        return getEndTimestamp();

      case METRICS:
        return getMetrics();
    }
    throw new java.lang.IllegalStateException();
  }

  /**
   * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
   * otherwise
   */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
      case VALUE:
        return isSetValue();
      case START_TIMESTAMP:
        return isSetStartTimestamp();
      case END_TIMESTAMP:
        return isSetEndTimestamp();
      case METRICS:
        return isSetMetrics();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof BackcastResponse) return this.equals((BackcastResponse) that);
    return false;
  }

  public boolean equals(BackcastResponse that) {
    if (that == null) return false;
    if (this == that) return true;

    boolean this_present_value = true;
    boolean that_present_value = true;
    if (this_present_value || that_present_value) {
      if (!(this_present_value && that_present_value)) return false;
      if (this.value != that.value) return false;
    }

    boolean this_present_startTimestamp = true;
    boolean that_present_startTimestamp = true;
    if (this_present_startTimestamp || that_present_startTimestamp) {
      if (!(this_present_startTimestamp && that_present_startTimestamp)) return false;
      if (this.startTimestamp != that.startTimestamp) return false;
    }

    boolean this_present_endTimestamp = true;
    boolean that_present_endTimestamp = true;
    if (this_present_endTimestamp || that_present_endTimestamp) {
      if (!(this_present_endTimestamp && that_present_endTimestamp)) return false;
      if (this.endTimestamp != that.endTimestamp) return false;
    }

    boolean this_present_metrics = true && this.isSetMetrics();
    boolean that_present_metrics = true && that.isSetMetrics();
    if (this_present_metrics || that_present_metrics) {
      if (!(this_present_metrics && that_present_metrics)) return false;
      if (!this.metrics.equals(that.metrics)) return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(value);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startTimestamp);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endTimestamp);

    hashCode = hashCode * 8191 + ((isSetMetrics()) ? 131071 : 524287);
    if (isSetMetrics()) hashCode = hashCode * 8191 + metrics.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BackcastResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetValue(), other.isSetValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value, other.value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStartTimestamp(), other.isSetStartTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTimestamp()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(this.startTimestamp, other.startTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEndTimestamp(), other.isSetEndTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndTimestamp()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(this.endTimestamp, other.endTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMetrics(), other.isSetMetrics());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetrics()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metrics, other.metrics);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot)
      throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BackcastResponse(");
    boolean first = true;

    sb.append("value:");
    sb.append(this.value);
    first = false;
    if (!first) sb.append(", ");
    sb.append("startTimestamp:");
    sb.append(this.startTimestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endTimestamp:");
    sb.append(this.endTimestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("metrics:");
    if (this.metrics == null) {
      sb.append("null");
    } else {
      sb.append(this.metrics);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in)
      throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and
      // doesn't call the default constructor.
      __isset_bitfield = 0;
      read(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BackcastResponseStandardSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public BackcastResponseStandardScheme getScheme() {
      return new BackcastResponseStandardScheme();
    }
  }

  private static class BackcastResponseStandardScheme
      extends org.apache.thrift.scheme.StandardScheme<BackcastResponse> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, BackcastResponse struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true) {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.value = iprot.readDouble();
              struct.setValueIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // START_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startTimestamp = iprot.readI64();
              struct.setStartTimestampIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // END_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endTimestamp = iprot.readI64();
              struct.setEndTimestampIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // METRICS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.metrics =
                    new java.util.HashMap<java.lang.String, java.lang.Double>(2 * _map0.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key1;
                double _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3) {
                  _key1 = iprot.readString();
                  _val2 = iprot.readDouble();
                  struct.metrics.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setMetricsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, BackcastResponse struct)
        throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VALUE_FIELD_DESC);
      oprot.writeDouble(struct.value);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(START_TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.startTimestamp);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(END_TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.endTimestamp);
      oprot.writeFieldEnd();
      if (struct.metrics != null) {
        oprot.writeFieldBegin(METRICS_FIELD_DESC);
        {
          oprot.writeMapBegin(
              new org.apache.thrift.protocol.TMap(
                  org.apache.thrift.protocol.TType.STRING,
                  org.apache.thrift.protocol.TType.DOUBLE,
                  struct.metrics.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.Double> _iter4 :
              struct.metrics.entrySet()) {
            oprot.writeString(_iter4.getKey());
            oprot.writeDouble(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
  }

  private static class BackcastResponseTupleSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public BackcastResponseTupleScheme getScheme() {
      return new BackcastResponseTupleScheme();
    }
  }

  private static class BackcastResponseTupleScheme
      extends org.apache.thrift.scheme.TupleScheme<BackcastResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BackcastResponse struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetValue()) {
        optionals.set(0);
      }
      if (struct.isSetStartTimestamp()) {
        optionals.set(1);
      }
      if (struct.isSetEndTimestamp()) {
        optionals.set(2);
      }
      if (struct.isSetMetrics()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetValue()) {
        oprot.writeDouble(struct.value);
      }
      if (struct.isSetStartTimestamp()) {
        oprot.writeI64(struct.startTimestamp);
      }
      if (struct.isSetEndTimestamp()) {
        oprot.writeI64(struct.endTimestamp);
      }
      if (struct.isSetMetrics()) {
        {
          oprot.writeI32(struct.metrics.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.Double> _iter5 :
              struct.metrics.entrySet()) {
            oprot.writeString(_iter5.getKey());
            oprot.writeDouble(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BackcastResponse struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.value = iprot.readDouble();
        struct.setValueIsSet(true);
      }
      if (incoming.get(1)) {
        struct.startTimestamp = iprot.readI64();
        struct.setStartTimestampIsSet(true);
      }
      if (incoming.get(2)) {
        struct.endTimestamp = iprot.readI64();
        struct.setEndTimestampIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map6 =
              iprot.readMapBegin(
                  org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE);
          struct.metrics =
              new java.util.HashMap<java.lang.String, java.lang.Double>(2 * _map6.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key7;
          double _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9) {
            _key7 = iprot.readString();
            _val8 = iprot.readDouble();
            struct.metrics.put(_key7, _val8);
          }
        }
        struct.setMetricsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
      org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
            ? STANDARD_SCHEME_FACTORY
            : TUPLE_SCHEME_FACTORY)
        .getScheme();
  }
}
