/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package org.softwareforce.iotvm.shared.event;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class QualityPropertiesIBO extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7106607812715165316L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"QualityPropertiesIBO\",\"namespace\":\"org.softwareforce.iotvm.shared.event\",\"fields\":[{\"name\":\"completeness\",\"type\":[\"double\",\"null\"]},{\"name\":\"timeliness\",\"type\":[\"double\",\"null\"]}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<QualityPropertiesIBO> ENCODER =
      new BinaryMessageEncoder<QualityPropertiesIBO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<QualityPropertiesIBO> DECODER =
      new BinaryMessageDecoder<QualityPropertiesIBO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<QualityPropertiesIBO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<QualityPropertiesIBO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<QualityPropertiesIBO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<QualityPropertiesIBO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this QualityPropertiesIBO to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a QualityPropertiesIBO from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a QualityPropertiesIBO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static QualityPropertiesIBO fromByteBuffer(java.nio.ByteBuffer b)
      throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Double completeness;
  private java.lang.Double timeliness;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public QualityPropertiesIBO() {}

  /**
   * All-args constructor.
   *
   * @param completeness The new value for completeness
   * @param timeliness The new value for timeliness
   */
  public QualityPropertiesIBO(java.lang.Double completeness, java.lang.Double timeliness) {
    this.completeness = completeness;
    this.timeliness = timeliness;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return completeness;
      case 1:
        return timeliness;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        completeness = (java.lang.Double) value$;
        break;
      case 1:
        timeliness = (java.lang.Double) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'completeness' field.
   *
   * @return The value of the 'completeness' field.
   */
  public java.lang.Double getCompleteness() {
    return completeness;
  }

  /**
   * Sets the value of the 'completeness' field.
   *
   * @param value the value to set.
   */
  public void setCompleteness(java.lang.Double value) {
    this.completeness = value;
  }

  /**
   * Gets the value of the 'timeliness' field.
   *
   * @return The value of the 'timeliness' field.
   */
  public java.lang.Double getTimeliness() {
    return timeliness;
  }

  /**
   * Sets the value of the 'timeliness' field.
   *
   * @param value the value to set.
   */
  public void setTimeliness(java.lang.Double value) {
    this.timeliness = value;
  }

  /**
   * Creates a new QualityPropertiesIBO RecordBuilder.
   *
   * @return A new QualityPropertiesIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder newBuilder() {
    return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder();
  }

  /**
   * Creates a new QualityPropertiesIBO RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new QualityPropertiesIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder newBuilder(
      org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder other) {
    if (other == null) {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder();
    } else {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder(other);
    }
  }

  /**
   * Creates a new QualityPropertiesIBO RecordBuilder by copying an existing QualityPropertiesIBO
   * instance.
   *
   * @param other The existing instance to copy.
   * @return A new QualityPropertiesIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder newBuilder(
      org.softwareforce.iotvm.shared.event.QualityPropertiesIBO other) {
    if (other == null) {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder();
    } else {
      return new org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder(other);
    }
  }

  /** RecordBuilder for QualityPropertiesIBO instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<QualityPropertiesIBO>
      implements org.apache.avro.data.RecordBuilder<QualityPropertiesIBO> {

    private java.lang.Double completeness;
    private java.lang.Double timeliness;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.completeness)) {
        this.completeness = data().deepCopy(fields()[0].schema(), other.completeness);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timeliness)) {
        this.timeliness = data().deepCopy(fields()[1].schema(), other.timeliness);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing QualityPropertiesIBO instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(org.softwareforce.iotvm.shared.event.QualityPropertiesIBO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.completeness)) {
        this.completeness = data().deepCopy(fields()[0].schema(), other.completeness);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeliness)) {
        this.timeliness = data().deepCopy(fields()[1].schema(), other.timeliness);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'completeness' field.
     *
     * @return The value.
     */
    public java.lang.Double getCompleteness() {
      return completeness;
    }

    /**
     * Sets the value of the 'completeness' field.
     *
     * @param value The value of 'completeness'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder setCompleteness(
        java.lang.Double value) {
      validate(fields()[0], value);
      this.completeness = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'completeness' field has been set.
     *
     * @return True if the 'completeness' field has been set, false otherwise.
     */
    public boolean hasCompleteness() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'completeness' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder clearCompleteness() {
      completeness = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'timeliness' field.
     *
     * @return The value.
     */
    public java.lang.Double getTimeliness() {
      return timeliness;
    }

    /**
     * Sets the value of the 'timeliness' field.
     *
     * @param value The value of 'timeliness'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder setTimeliness(
        java.lang.Double value) {
      validate(fields()[1], value);
      this.timeliness = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'timeliness' field has been set.
     *
     * @return True if the 'timeliness' field has been set, false otherwise.
     */
    public boolean hasTimeliness() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'timeliness' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.QualityPropertiesIBO.Builder clearTimeliness() {
      timeliness = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public QualityPropertiesIBO build() {
      try {
        QualityPropertiesIBO record = new QualityPropertiesIBO();
        record.completeness =
            fieldSetFlags()[0] ? this.completeness : (java.lang.Double) defaultValue(fields()[0]);
        record.timeliness =
            fieldSetFlags()[1] ? this.timeliness : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<QualityPropertiesIBO> WRITER$ =
      (org.apache.avro.io.DatumWriter<QualityPropertiesIBO>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<QualityPropertiesIBO> READER$ =
      (org.apache.avro.io.DatumReader<QualityPropertiesIBO>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    if (this.completeness == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeDouble(this.completeness);
    }

    if (this.timeliness == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeDouble(this.timeliness);
    }
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 0) {
        in.readNull();
        this.completeness = null;
      } else {
        this.completeness = in.readDouble();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.timeliness = null;
      } else {
        this.timeliness = in.readDouble();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            if (in.readIndex() != 0) {
              in.readNull();
              this.completeness = null;
            } else {
              this.completeness = in.readDouble();
            }
            break;

          case 1:
            if (in.readIndex() != 0) {
              in.readNull();
              this.timeliness = null;
            } else {
              this.timeliness = in.readDouble();
            }
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
