/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package org.softwareforce.iotvm.shared.event;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class SensorTelemetryMeasurementEventIBO extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4595491639266904111L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"SensorTelemetryMeasurementEventIBO\",\"namespace\":\"org.softwareforce.iotvm.shared.event\",\"fields\":[{\"name\":\"sensorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"measurement\",\"type\":{\"type\":\"record\",\"name\":\"MeasurementIBO\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"value\",\"type\":[\"double\",\"null\"]},{\"name\":\"unit\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}},{\"name\":\"timestamps\",\"type\":{\"type\":\"record\",\"name\":\"TimestampsIBO\",\"fields\":[{\"name\":\"defaultTimestamp\",\"type\":[\"long\",\"null\"]},{\"name\":\"timestamps\",\"type\":{\"type\":\"map\",\"values\":[\"long\",\"null\"],\"avro.java.string\":\"String\"}}]}},{\"name\":\"identifiers\",\"type\":{\"type\":\"record\",\"name\":\"IdentifiersIBO\",\"fields\":[{\"name\":\"clientSideId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"avro.java.string\":\"String\"},{\"name\":\"correlationIds\",\"type\":{\"type\":\"map\",\"values\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"avro.java.string\":\"String\"}}]}},{\"name\":\"additional\",\"type\":{\"type\":\"map\",\"values\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"int\",\"double\",\"long\",\"boolean\",\"null\"],\"avro.java.string\":\"String\"}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SensorTelemetryMeasurementEventIBO> ENCODER =
      new BinaryMessageEncoder<SensorTelemetryMeasurementEventIBO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SensorTelemetryMeasurementEventIBO> DECODER =
      new BinaryMessageDecoder<SensorTelemetryMeasurementEventIBO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SensorTelemetryMeasurementEventIBO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SensorTelemetryMeasurementEventIBO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SensorTelemetryMeasurementEventIBO> createDecoder(
      SchemaStore resolver) {
    return new BinaryMessageDecoder<SensorTelemetryMeasurementEventIBO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SensorTelemetryMeasurementEventIBO to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SensorTelemetryMeasurementEventIBO from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SensorTelemetryMeasurementEventIBO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static SensorTelemetryMeasurementEventIBO fromByteBuffer(java.nio.ByteBuffer b)
      throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String sensorId;
  private org.softwareforce.iotvm.shared.event.MeasurementIBO measurement;
  private org.softwareforce.iotvm.shared.event.TimestampsIBO timestamps;
  private org.softwareforce.iotvm.shared.event.IdentifiersIBO identifiers;
  private java.util.Map<java.lang.String, java.lang.Object> additional;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public SensorTelemetryMeasurementEventIBO() {}

  /**
   * All-args constructor.
   *
   * @param sensorId The new value for sensorId
   * @param measurement The new value for measurement
   * @param timestamps The new value for timestamps
   * @param identifiers The new value for identifiers
   * @param additional The new value for additional
   */
  public SensorTelemetryMeasurementEventIBO(
      java.lang.String sensorId,
      org.softwareforce.iotvm.shared.event.MeasurementIBO measurement,
      org.softwareforce.iotvm.shared.event.TimestampsIBO timestamps,
      org.softwareforce.iotvm.shared.event.IdentifiersIBO identifiers,
      java.util.Map<java.lang.String, java.lang.Object> additional) {
    this.sensorId = sensorId;
    this.measurement = measurement;
    this.timestamps = timestamps;
    this.identifiers = identifiers;
    this.additional = additional;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return sensorId;
      case 1:
        return measurement;
      case 2:
        return timestamps;
      case 3:
        return identifiers;
      case 4:
        return additional;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        sensorId = value$ != null ? value$.toString() : null;
        break;
      case 1:
        measurement = (org.softwareforce.iotvm.shared.event.MeasurementIBO) value$;
        break;
      case 2:
        timestamps = (org.softwareforce.iotvm.shared.event.TimestampsIBO) value$;
        break;
      case 3:
        identifiers = (org.softwareforce.iotvm.shared.event.IdentifiersIBO) value$;
        break;
      case 4:
        additional = (java.util.Map<java.lang.String, java.lang.Object>) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensorId' field.
   *
   * @return The value of the 'sensorId' field.
   */
  public java.lang.String getSensorId() {
    return sensorId;
  }

  /**
   * Sets the value of the 'sensorId' field.
   *
   * @param value the value to set.
   */
  public void setSensorId(java.lang.String value) {
    this.sensorId = value;
  }

  /**
   * Gets the value of the 'measurement' field.
   *
   * @return The value of the 'measurement' field.
   */
  public org.softwareforce.iotvm.shared.event.MeasurementIBO getMeasurement() {
    return measurement;
  }

  /**
   * Sets the value of the 'measurement' field.
   *
   * @param value the value to set.
   */
  public void setMeasurement(org.softwareforce.iotvm.shared.event.MeasurementIBO value) {
    this.measurement = value;
  }

  /**
   * Gets the value of the 'timestamps' field.
   *
   * @return The value of the 'timestamps' field.
   */
  public org.softwareforce.iotvm.shared.event.TimestampsIBO getTimestamps() {
    return timestamps;
  }

  /**
   * Sets the value of the 'timestamps' field.
   *
   * @param value the value to set.
   */
  public void setTimestamps(org.softwareforce.iotvm.shared.event.TimestampsIBO value) {
    this.timestamps = value;
  }

  /**
   * Gets the value of the 'identifiers' field.
   *
   * @return The value of the 'identifiers' field.
   */
  public org.softwareforce.iotvm.shared.event.IdentifiersIBO getIdentifiers() {
    return identifiers;
  }

  /**
   * Sets the value of the 'identifiers' field.
   *
   * @param value the value to set.
   */
  public void setIdentifiers(org.softwareforce.iotvm.shared.event.IdentifiersIBO value) {
    this.identifiers = value;
  }

  /**
   * Gets the value of the 'additional' field.
   *
   * @return The value of the 'additional' field.
   */
  public java.util.Map<java.lang.String, java.lang.Object> getAdditional() {
    return additional;
  }

  /**
   * Sets the value of the 'additional' field.
   *
   * @param value the value to set.
   */
  public void setAdditional(java.util.Map<java.lang.String, java.lang.Object> value) {
    this.additional = value;
  }

  /**
   * Creates a new SensorTelemetryMeasurementEventIBO RecordBuilder.
   *
   * @return A new SensorTelemetryMeasurementEventIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
      newBuilder() {
    return new org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder();
  }

  /**
   * Creates a new SensorTelemetryMeasurementEventIBO RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new SensorTelemetryMeasurementEventIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
      newBuilder(
          org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder other) {
    if (other == null) {
      return new org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder();
    } else {
      return new org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder(
          other);
    }
  }

  /**
   * Creates a new SensorTelemetryMeasurementEventIBO RecordBuilder by copying an existing
   * SensorTelemetryMeasurementEventIBO instance.
   *
   * @param other The existing instance to copy.
   * @return A new SensorTelemetryMeasurementEventIBO RecordBuilder
   */
  public static org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
      newBuilder(org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO other) {
    if (other == null) {
      return new org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder();
    } else {
      return new org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder(
          other);
    }
  }

  /** RecordBuilder for SensorTelemetryMeasurementEventIBO instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorTelemetryMeasurementEventIBO>
      implements org.apache.avro.data.RecordBuilder<SensorTelemetryMeasurementEventIBO> {

    private java.lang.String sensorId;
    private org.softwareforce.iotvm.shared.event.MeasurementIBO measurement;
    private org.softwareforce.iotvm.shared.event.MeasurementIBO.Builder measurementBuilder;
    private org.softwareforce.iotvm.shared.event.TimestampsIBO timestamps;
    private org.softwareforce.iotvm.shared.event.TimestampsIBO.Builder timestampsBuilder;
    private org.softwareforce.iotvm.shared.event.IdentifiersIBO identifiers;
    private org.softwareforce.iotvm.shared.event.IdentifiersIBO.Builder identifiersBuilder;
    private java.util.Map<java.lang.String, java.lang.Object> additional;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(
        org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.measurement)) {
        this.measurement = data().deepCopy(fields()[1].schema(), other.measurement);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasMeasurementBuilder()) {
        this.measurementBuilder =
            org.softwareforce.iotvm.shared.event.MeasurementIBO.newBuilder(
                other.getMeasurementBuilder());
      }
      if (isValidValue(fields()[2], other.timestamps)) {
        this.timestamps = data().deepCopy(fields()[2].schema(), other.timestamps);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasTimestampsBuilder()) {
        this.timestampsBuilder =
            org.softwareforce.iotvm.shared.event.TimestampsIBO.newBuilder(
                other.getTimestampsBuilder());
      }
      if (isValidValue(fields()[3], other.identifiers)) {
        this.identifiers = data().deepCopy(fields()[3].schema(), other.identifiers);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasIdentifiersBuilder()) {
        this.identifiersBuilder =
            org.softwareforce.iotvm.shared.event.IdentifiersIBO.newBuilder(
                other.getIdentifiersBuilder());
      }
      if (isValidValue(fields()[4], other.additional)) {
        this.additional = data().deepCopy(fields()[4].schema(), other.additional);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing SensorTelemetryMeasurementEventIBO instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.measurement)) {
        this.measurement = data().deepCopy(fields()[1].schema(), other.measurement);
        fieldSetFlags()[1] = true;
      }
      this.measurementBuilder = null;
      if (isValidValue(fields()[2], other.timestamps)) {
        this.timestamps = data().deepCopy(fields()[2].schema(), other.timestamps);
        fieldSetFlags()[2] = true;
      }
      this.timestampsBuilder = null;
      if (isValidValue(fields()[3], other.identifiers)) {
        this.identifiers = data().deepCopy(fields()[3].schema(), other.identifiers);
        fieldSetFlags()[3] = true;
      }
      this.identifiersBuilder = null;
      if (isValidValue(fields()[4], other.additional)) {
        this.additional = data().deepCopy(fields()[4].schema(), other.additional);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Gets the value of the 'sensorId' field.
     *
     * @return The value.
     */
    public java.lang.String getSensorId() {
      return sensorId;
    }

    /**
     * Sets the value of the 'sensorId' field.
     *
     * @param value The value of 'sensorId'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setSensorId(java.lang.String value) {
      validate(fields()[0], value);
      this.sensorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'sensorId' field has been set.
     *
     * @return True if the 'sensorId' field has been set, false otherwise.
     */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'sensorId' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        clearSensorId() {
      sensorId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'measurement' field.
     *
     * @return The value.
     */
    public org.softwareforce.iotvm.shared.event.MeasurementIBO getMeasurement() {
      return measurement;
    }

    /**
     * Sets the value of the 'measurement' field.
     *
     * @param value The value of 'measurement'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setMeasurement(org.softwareforce.iotvm.shared.event.MeasurementIBO value) {
      validate(fields()[1], value);
      this.measurementBuilder = null;
      this.measurement = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'measurement' field has been set.
     *
     * @return True if the 'measurement' field has been set, false otherwise.
     */
    public boolean hasMeasurement() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'measurement' field and creates one if it doesn't exist
     * yet.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.MeasurementIBO.Builder getMeasurementBuilder() {
      if (measurementBuilder == null) {
        if (hasMeasurement()) {
          setMeasurementBuilder(
              org.softwareforce.iotvm.shared.event.MeasurementIBO.newBuilder(measurement));
        } else {
          setMeasurementBuilder(org.softwareforce.iotvm.shared.event.MeasurementIBO.newBuilder());
        }
      }
      return measurementBuilder;
    }

    /**
     * Sets the Builder instance for the 'measurement' field
     *
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setMeasurementBuilder(org.softwareforce.iotvm.shared.event.MeasurementIBO.Builder value) {
      clearMeasurement();
      measurementBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'measurement' field has an active Builder instance
     *
     * @return True if the 'measurement' field has an active Builder instance
     */
    public boolean hasMeasurementBuilder() {
      return measurementBuilder != null;
    }

    /**
     * Clears the value of the 'measurement' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        clearMeasurement() {
      measurement = null;
      measurementBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'timestamps' field.
     *
     * @return The value.
     */
    public org.softwareforce.iotvm.shared.event.TimestampsIBO getTimestamps() {
      return timestamps;
    }

    /**
     * Sets the value of the 'timestamps' field.
     *
     * @param value The value of 'timestamps'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setTimestamps(org.softwareforce.iotvm.shared.event.TimestampsIBO value) {
      validate(fields()[2], value);
      this.timestampsBuilder = null;
      this.timestamps = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'timestamps' field has been set.
     *
     * @return True if the 'timestamps' field has been set, false otherwise.
     */
    public boolean hasTimestamps() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'timestamps' field and creates one if it doesn't exist yet.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.TimestampsIBO.Builder getTimestampsBuilder() {
      if (timestampsBuilder == null) {
        if (hasTimestamps()) {
          setTimestampsBuilder(
              org.softwareforce.iotvm.shared.event.TimestampsIBO.newBuilder(timestamps));
        } else {
          setTimestampsBuilder(org.softwareforce.iotvm.shared.event.TimestampsIBO.newBuilder());
        }
      }
      return timestampsBuilder;
    }

    /**
     * Sets the Builder instance for the 'timestamps' field
     *
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setTimestampsBuilder(org.softwareforce.iotvm.shared.event.TimestampsIBO.Builder value) {
      clearTimestamps();
      timestampsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'timestamps' field has an active Builder instance
     *
     * @return True if the 'timestamps' field has an active Builder instance
     */
    public boolean hasTimestampsBuilder() {
      return timestampsBuilder != null;
    }

    /**
     * Clears the value of the 'timestamps' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        clearTimestamps() {
      timestamps = null;
      timestampsBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'identifiers' field.
     *
     * @return The value.
     */
    public org.softwareforce.iotvm.shared.event.IdentifiersIBO getIdentifiers() {
      return identifiers;
    }

    /**
     * Sets the value of the 'identifiers' field.
     *
     * @param value The value of 'identifiers'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setIdentifiers(org.softwareforce.iotvm.shared.event.IdentifiersIBO value) {
      validate(fields()[3], value);
      this.identifiersBuilder = null;
      this.identifiers = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'identifiers' field has been set.
     *
     * @return True if the 'identifiers' field has been set, false otherwise.
     */
    public boolean hasIdentifiers() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'identifiers' field and creates one if it doesn't exist
     * yet.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.IdentifiersIBO.Builder getIdentifiersBuilder() {
      if (identifiersBuilder == null) {
        if (hasIdentifiers()) {
          setIdentifiersBuilder(
              org.softwareforce.iotvm.shared.event.IdentifiersIBO.newBuilder(identifiers));
        } else {
          setIdentifiersBuilder(org.softwareforce.iotvm.shared.event.IdentifiersIBO.newBuilder());
        }
      }
      return identifiersBuilder;
    }

    /**
     * Sets the Builder instance for the 'identifiers' field
     *
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setIdentifiersBuilder(org.softwareforce.iotvm.shared.event.IdentifiersIBO.Builder value) {
      clearIdentifiers();
      identifiersBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'identifiers' field has an active Builder instance
     *
     * @return True if the 'identifiers' field has an active Builder instance
     */
    public boolean hasIdentifiersBuilder() {
      return identifiersBuilder != null;
    }

    /**
     * Clears the value of the 'identifiers' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        clearIdentifiers() {
      identifiers = null;
      identifiersBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'additional' field.
     *
     * @return The value.
     */
    public java.util.Map<java.lang.String, java.lang.Object> getAdditional() {
      return additional;
    }

    /**
     * Sets the value of the 'additional' field.
     *
     * @param value The value of 'additional'.
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        setAdditional(java.util.Map<java.lang.String, java.lang.Object> value) {
      validate(fields()[4], value);
      this.additional = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'additional' field has been set.
     *
     * @return True if the 'additional' field has been set, false otherwise.
     */
    public boolean hasAdditional() {
      return fieldSetFlags()[4];
    }

    /**
     * Clears the value of the 'additional' field.
     *
     * @return This builder.
     */
    public org.softwareforce.iotvm.shared.event.SensorTelemetryMeasurementEventIBO.Builder
        clearAdditional() {
      additional = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SensorTelemetryMeasurementEventIBO build() {
      try {
        SensorTelemetryMeasurementEventIBO record = new SensorTelemetryMeasurementEventIBO();
        record.sensorId =
            fieldSetFlags()[0] ? this.sensorId : (java.lang.String) defaultValue(fields()[0]);
        if (measurementBuilder != null) {
          try {
            record.measurement = this.measurementBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("measurement"));
            throw e;
          }
        } else {
          record.measurement =
              fieldSetFlags()[1]
                  ? this.measurement
                  : (org.softwareforce.iotvm.shared.event.MeasurementIBO) defaultValue(fields()[1]);
        }
        if (timestampsBuilder != null) {
          try {
            record.timestamps = this.timestampsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("timestamps"));
            throw e;
          }
        } else {
          record.timestamps =
              fieldSetFlags()[2]
                  ? this.timestamps
                  : (org.softwareforce.iotvm.shared.event.TimestampsIBO) defaultValue(fields()[2]);
        }
        if (identifiersBuilder != null) {
          try {
            record.identifiers = this.identifiersBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("identifiers"));
            throw e;
          }
        } else {
          record.identifiers =
              fieldSetFlags()[3]
                  ? this.identifiers
                  : (org.softwareforce.iotvm.shared.event.IdentifiersIBO) defaultValue(fields()[3]);
        }
        record.additional =
            fieldSetFlags()[4]
                ? this.additional
                : (java.util.Map<java.lang.String, java.lang.Object>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SensorTelemetryMeasurementEventIBO> WRITER$ =
      (org.apache.avro.io.DatumWriter<SensorTelemetryMeasurementEventIBO>)
          MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SensorTelemetryMeasurementEventIBO> READER$ =
      (org.apache.avro.io.DatumReader<SensorTelemetryMeasurementEventIBO>)
          MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }
}
