#
# Autogenerated by Thrift Compiler (0.18.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import (
    TType,
    TMessageType,
    TFrozenDict,
    TException,
    TApplicationException,
)
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import iotvm_extensions.shared.base.BaseService
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport

all_structs = []


class Iface(iotvm_extensions.shared.base.BaseService.Iface):
    """
    Defines the (fabrication) backcasting service contract.

    """

    def ensure(self, scope):
        """
        NOTICE: When active, idempotence must be ensured.

        Parameters:
         - scope

        """
        pass

    def backcast(self, scope, request):
        """
        Parameters:
         - scope
         - request

        """
        pass


class Client(iotvm_extensions.shared.base.BaseService.Client, Iface):
    """
    Defines the (fabrication) backcasting service contract.

    """

    def __init__(self, iprot, oprot=None):
        iotvm_extensions.shared.base.BaseService.Client.__init__(self, iprot, oprot)

    def ensure(self, scope):
        """
        NOTICE: When active, idempotence must be ensured.

        Parameters:
         - scope

        """
        self.send_ensure(scope)

    def send_ensure(self, scope):
        self._oprot.writeMessageBegin("ensure", TMessageType.ONEWAY, self._seqid)
        args = ensure_args()
        args.scope = scope
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def backcast(self, scope, request):
        """
        Parameters:
         - scope
         - request

        """
        self.send_backcast(scope, request)
        return self.recv_backcast()

    def send_backcast(self, scope, request):
        self._oprot.writeMessageBegin("backcast", TMessageType.CALL, self._seqid)
        args = backcast_args()
        args.scope = scope
        args.request = request
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_backcast(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = backcast_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.exc is not None:
            raise result.exc
        raise TApplicationException(TApplicationException.MISSING_RESULT, "backcast failed: unknown result")


class Processor(iotvm_extensions.shared.base.BaseService.Processor, Iface, TProcessor):
    def __init__(self, handler):
        iotvm_extensions.shared.base.BaseService.Processor.__init__(self, handler)
        self._processMap["ensure"] = Processor.process_ensure
        self._processMap["backcast"] = Processor.process_backcast
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, "Unknown function %s" % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_ensure(self, seqid, iprot, oprot):
        args = ensure_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.ensure(args.scope)
        except TTransport.TTransportException:
            raise
        except Exception:
            logging.exception("Exception in oneway handler")

    def process_backcast(self, seqid, iprot, oprot):
        args = backcast_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = backcast_result()
        try:
            result.success = self._handler.backcast(args.scope, args.request)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except BackcastException as exc:
            msg_type = TMessageType.REPLY
            result.exc = exc
        except TApplicationException as ex:
            logging.exception("TApplication exception in handler")
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception("Unexpected exception in handler")
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, "Internal error")
        oprot.writeMessageBegin("backcast", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES


class ensure_args(object):
    """
    Attributes:
     - scope

    """

    def __init__(
        self,
        scope=None,
    ):
        self.scope = scope

    def read(self, iprot):
        if (
            iprot._fast_decode is not None
            and isinstance(iprot.trans, TTransport.CReadableTransport)
            and self.thrift_spec is not None
        ):
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.scope = BackcastScope()
                    self.scope.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin("ensure_args")
        if self.scope is not None:
            oprot.writeFieldBegin("scope", TType.STRUCT, 1)
            self.scope.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ["%s=%r" % (key, value) for key, value in self.__dict__.items()]
        return "%s(%s)" % (self.__class__.__name__, ", ".join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


all_structs.append(ensure_args)
ensure_args.thrift_spec = (
    None,  # 0
    (
        1,
        TType.STRUCT,
        "scope",
        [BackcastScope, None],
        None,
    ),  # 1
)


class backcast_args(object):
    """
    Attributes:
     - scope
     - request

    """

    def __init__(
        self,
        scope=None,
        request=None,
    ):
        self.scope = scope
        self.request = request

    def read(self, iprot):
        if (
            iprot._fast_decode is not None
            and isinstance(iprot.trans, TTransport.CReadableTransport)
            and self.thrift_spec is not None
        ):
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.scope = BackcastScope()
                    self.scope.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.request = BackcastRequest()
                    self.request.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin("backcast_args")
        if self.scope is not None:
            oprot.writeFieldBegin("scope", TType.STRUCT, 1)
            self.scope.write(oprot)
            oprot.writeFieldEnd()
        if self.request is not None:
            oprot.writeFieldBegin("request", TType.STRUCT, 2)
            self.request.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ["%s=%r" % (key, value) for key, value in self.__dict__.items()]
        return "%s(%s)" % (self.__class__.__name__, ", ".join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


all_structs.append(backcast_args)
backcast_args.thrift_spec = (
    None,  # 0
    (
        1,
        TType.STRUCT,
        "scope",
        [BackcastScope, None],
        None,
    ),  # 1
    (
        2,
        TType.STRUCT,
        "request",
        [BackcastRequest, None],
        None,
    ),  # 2
)


class backcast_result(object):
    """
    Attributes:
     - success
     - exc

    """

    def __init__(
        self,
        success=None,
        exc=None,
    ):
        self.success = success
        self.exc = exc

    def read(self, iprot):
        if (
            iprot._fast_decode is not None
            and isinstance(iprot.trans, TTransport.CReadableTransport)
            and self.thrift_spec is not None
        ):
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = BackcastResponse()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.exc = BackcastException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin("backcast_result")
        if self.success is not None:
            oprot.writeFieldBegin("success", TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.exc is not None:
            oprot.writeFieldBegin("exc", TType.STRUCT, 1)
            self.exc.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ["%s=%r" % (key, value) for key, value in self.__dict__.items()]
        return "%s(%s)" % (self.__class__.__name__, ", ".join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


all_structs.append(backcast_result)
backcast_result.thrift_spec = (
    (
        0,
        TType.STRUCT,
        "success",
        [BackcastResponse, None],
        None,
    ),  # 0
    (
        1,
        TType.STRUCT,
        "exc",
        [BackcastException, None],
        None,
    ),  # 1
)
fix_spec(all_structs)
del all_structs
