/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * <p>DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.softwareforce.iotvm.shared.extensions.sensing_recording.spec;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(
    value = "Autogenerated by Thrift Compiler (0.18.1)",
    date = "2023-09-02")
public class RecordedSensorData
    implements org.apache.thrift.TBase<RecordedSensorData, RecordedSensorData._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<RecordedSensorData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
      new org.apache.thrift.protocol.TStruct("RecordedSensorData");

  private static final org.apache.thrift.protocol.TField SENSOR_ID_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "sensorId", org.apache.thrift.protocol.TType.STRING, (short) 1);
  private static final org.apache.thrift.protocol.TField MEASUREMENTS_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "measurements", org.apache.thrift.protocol.TType.LIST, (short) 2);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "timestamp", org.apache.thrift.protocol.TType.I64, (short) 3);
  private static final org.apache.thrift.protocol.TField ADDITIONAL_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "additional", org.apache.thrift.protocol.TType.MAP, (short) 4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
      new RecordedSensorDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
      new RecordedSensorDataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String sensorId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<RecordedSensorMeasurement>
      measurements; // required
  public long timestamp; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.String>
      additional; // required

  /**
   * The set of fields this struct contains, along with convenience methods for finding and
   * manipulating them.
   */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SENSOR_ID((short) 1, "sensorId"),
    MEASUREMENTS((short) 2, "measurements"),
    TIMESTAMP((short) 3, "timestamp"),
    ADDITIONAL((short) 4, "additional");

    private static final java.util.Map<java.lang.String, _Fields> byName =
        new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /** Find the _Fields constant that matches fieldId, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch (fieldId) {
        case 1: // SENSOR_ID
          return SENSOR_ID;
        case 2: // MEASUREMENTS
          return MEASUREMENTS;
        case 3: // TIMESTAMP
          return TIMESTAMP;
        case 4: // ADDITIONAL
          return ADDITIONAL;
        default:
          return null;
      }
    }

    /** Find the _Fields constant that matches fieldId, throwing an exception if it is not found. */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null)
        throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /** Find the _Fields constant that matches name, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMP_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
        new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(
        _Fields.SENSOR_ID,
        new org.apache.thrift.meta_data.FieldMetaData(
            "sensorId",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(
        _Fields.MEASUREMENTS,
        new org.apache.thrift.meta_data.FieldMetaData(
            "measurements",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.ListMetaData(
                org.apache.thrift.protocol.TType.LIST,
                new org.apache.thrift.meta_data.StructMetaData(
                    org.apache.thrift.protocol.TType.STRUCT, RecordedSensorMeasurement.class))));
    tmpMap.put(
        _Fields.TIMESTAMP,
        new org.apache.thrift.meta_data.FieldMetaData(
            "timestamp",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(
        _Fields.ADDITIONAL,
        new org.apache.thrift.meta_data.FieldMetaData(
            "additional",
            org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.MapMetaData(
                org.apache.thrift.protocol.TType.MAP,
                new org.apache.thrift.meta_data.FieldValueMetaData(
                    org.apache.thrift.protocol.TType.STRING),
                new org.apache.thrift.meta_data.FieldValueMetaData(
                    org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
        RecordedSensorData.class, metaDataMap);
  }

  public RecordedSensorData() {}

  public RecordedSensorData(
      java.lang.String sensorId,
      java.util.List<RecordedSensorMeasurement> measurements,
      long timestamp,
      java.util.Map<java.lang.String, java.lang.String> additional) {
    this();
    this.sensorId = sensorId;
    this.measurements = measurements;
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    this.additional = additional;
  }

  /** Performs a deep copy on <i>other</i>. */
  public RecordedSensorData(RecordedSensorData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetSensorId()) {
      this.sensorId = other.sensorId;
    }
    if (other.isSetMeasurements()) {
      java.util.List<RecordedSensorMeasurement> __this__measurements =
          new java.util.ArrayList<RecordedSensorMeasurement>(other.measurements.size());
      for (RecordedSensorMeasurement other_element : other.measurements) {
        __this__measurements.add(new RecordedSensorMeasurement(other_element));
      }
      this.measurements = __this__measurements;
    }
    this.timestamp = other.timestamp;
    if (other.isSetAdditional()) {
      java.util.Map<java.lang.String, java.lang.String> __this__additional =
          new java.util.HashMap<java.lang.String, java.lang.String>(other.additional);
      this.additional = __this__additional;
    }
  }

  @Override
  public RecordedSensorData deepCopy() {
    return new RecordedSensorData(this);
  }

  @Override
  public void clear() {
    this.sensorId = null;
    this.measurements = null;
    setTimestampIsSet(false);
    this.timestamp = 0;
    this.additional = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSensorId() {
    return this.sensorId;
  }

  public RecordedSensorData setSensorId(
      @org.apache.thrift.annotation.Nullable java.lang.String sensorId) {
    this.sensorId = sensorId;
    return this;
  }

  public void unsetSensorId() {
    this.sensorId = null;
  }

  /** Returns true if field sensorId is set (has been assigned a value) and false otherwise */
  public boolean isSetSensorId() {
    return this.sensorId != null;
  }

  public void setSensorIdIsSet(boolean value) {
    if (!value) {
      this.sensorId = null;
    }
  }

  public int getMeasurementsSize() {
    return (this.measurements == null) ? 0 : this.measurements.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<RecordedSensorMeasurement> getMeasurementsIterator() {
    return (this.measurements == null) ? null : this.measurements.iterator();
  }

  public void addToMeasurements(RecordedSensorMeasurement elem) {
    if (this.measurements == null) {
      this.measurements = new java.util.ArrayList<RecordedSensorMeasurement>();
    }
    this.measurements.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<RecordedSensorMeasurement> getMeasurements() {
    return this.measurements;
  }

  public RecordedSensorData setMeasurements(
      @org.apache.thrift.annotation.Nullable
          java.util.List<RecordedSensorMeasurement> measurements) {
    this.measurements = measurements;
    return this;
  }

  public void unsetMeasurements() {
    this.measurements = null;
  }

  /** Returns true if field measurements is set (has been assigned a value) and false otherwise */
  public boolean isSetMeasurements() {
    return this.measurements != null;
  }

  public void setMeasurementsIsSet(boolean value) {
    if (!value) {
      this.measurements = null;
    }
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public RecordedSensorData setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public int getAdditionalSize() {
    return (this.additional == null) ? 0 : this.additional.size();
  }

  public void putToAdditional(java.lang.String key, java.lang.String val) {
    if (this.additional == null) {
      this.additional = new java.util.HashMap<java.lang.String, java.lang.String>();
    }
    this.additional.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String, java.lang.String> getAdditional() {
    return this.additional;
  }

  public RecordedSensorData setAdditional(
      @org.apache.thrift.annotation.Nullable
          java.util.Map<java.lang.String, java.lang.String> additional) {
    this.additional = additional;
    return this;
  }

  public void unsetAdditional() {
    this.additional = null;
  }

  /** Returns true if field additional is set (has been assigned a value) and false otherwise */
  public boolean isSetAdditional() {
    return this.additional != null;
  }

  public void setAdditionalIsSet(boolean value) {
    if (!value) {
      this.additional = null;
    }
  }

  @Override
  public void setFieldValue(
      _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
      case SENSOR_ID:
        if (value == null) {
          unsetSensorId();
        } else {
          setSensorId((java.lang.String) value);
        }
        break;

      case MEASUREMENTS:
        if (value == null) {
          unsetMeasurements();
        } else {
          setMeasurements((java.util.List<RecordedSensorMeasurement>) value);
        }
        break;

      case TIMESTAMP:
        if (value == null) {
          unsetTimestamp();
        } else {
          setTimestamp((java.lang.Long) value);
        }
        break;

      case ADDITIONAL:
        if (value == null) {
          unsetAdditional();
        } else {
          setAdditional((java.util.Map<java.lang.String, java.lang.String>) value);
        }
        break;
    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
      case SENSOR_ID:
        return getSensorId();

      case MEASUREMENTS:
        return getMeasurements();

      case TIMESTAMP:
        return getTimestamp();

      case ADDITIONAL:
        return getAdditional();
    }
    throw new java.lang.IllegalStateException();
  }

  /**
   * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
   * otherwise
   */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
      case SENSOR_ID:
        return isSetSensorId();
      case MEASUREMENTS:
        return isSetMeasurements();
      case TIMESTAMP:
        return isSetTimestamp();
      case ADDITIONAL:
        return isSetAdditional();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RecordedSensorData) return this.equals((RecordedSensorData) that);
    return false;
  }

  public boolean equals(RecordedSensorData that) {
    if (that == null) return false;
    if (this == that) return true;

    boolean this_present_sensorId = true && this.isSetSensorId();
    boolean that_present_sensorId = true && that.isSetSensorId();
    if (this_present_sensorId || that_present_sensorId) {
      if (!(this_present_sensorId && that_present_sensorId)) return false;
      if (!this.sensorId.equals(that.sensorId)) return false;
    }

    boolean this_present_measurements = true && this.isSetMeasurements();
    boolean that_present_measurements = true && that.isSetMeasurements();
    if (this_present_measurements || that_present_measurements) {
      if (!(this_present_measurements && that_present_measurements)) return false;
      if (!this.measurements.equals(that.measurements)) return false;
    }

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp)) return false;
      if (this.timestamp != that.timestamp) return false;
    }

    boolean this_present_additional = true && this.isSetAdditional();
    boolean that_present_additional = true && that.isSetAdditional();
    if (this_present_additional || that_present_additional) {
      if (!(this_present_additional && that_present_additional)) return false;
      if (!this.additional.equals(that.additional)) return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSensorId()) ? 131071 : 524287);
    if (isSetSensorId()) hashCode = hashCode * 8191 + sensorId.hashCode();

    hashCode = hashCode * 8191 + ((isSetMeasurements()) ? 131071 : 524287);
    if (isSetMeasurements()) hashCode = hashCode * 8191 + measurements.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timestamp);

    hashCode = hashCode * 8191 + ((isSetAdditional()) ? 131071 : 524287);
    if (isSetAdditional()) hashCode = hashCode * 8191 + additional.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RecordedSensorData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSensorId(), other.isSetSensorId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSensorId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sensorId, other.sensorId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMeasurements(), other.isSetMeasurements());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMeasurements()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(this.measurements, other.measurements);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTimestamp(), other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAdditional(), other.isSetAdditional());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdditional()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.additional, other.additional);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot)
      throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RecordedSensorData(");
    boolean first = true;

    sb.append("sensorId:");
    if (this.sensorId == null) {
      sb.append("null");
    } else {
      sb.append(this.sensorId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("measurements:");
    if (this.measurements == null) {
      sb.append("null");
    } else {
      sb.append(this.measurements);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("additional:");
    if (this.additional == null) {
      sb.append("null");
    } else {
      sb.append(this.additional);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in)
      throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and
      // doesn't call the default constructor.
      __isset_bitfield = 0;
      read(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecordedSensorDataStandardSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RecordedSensorDataStandardScheme getScheme() {
      return new RecordedSensorDataStandardScheme();
    }
  }

  private static class RecordedSensorDataStandardScheme
      extends org.apache.thrift.scheme.StandardScheme<RecordedSensorData> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RecordedSensorData struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true) {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // SENSOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sensorId = iprot.readString();
              struct.setSensorIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MEASUREMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.measurements =
                    new java.util.ArrayList<RecordedSensorMeasurement>(_list0.size);
                @org.apache.thrift.annotation.Nullable RecordedSensorMeasurement _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2) {
                  _elem1 = new RecordedSensorMeasurement();
                  _elem1.read(iprot);
                  struct.measurements.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setMeasurementsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ADDITIONAL
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map3 = iprot.readMapBegin();
                struct.additional =
                    new java.util.HashMap<java.lang.String, java.lang.String>(2 * _map3.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key4;
                @org.apache.thrift.annotation.Nullable java.lang.String _val5;
                for (int _i6 = 0; _i6 < _map3.size; ++_i6) {
                  _key4 = iprot.readString();
                  _val5 = iprot.readString();
                  struct.additional.put(_key4, _val5);
                }
                iprot.readMapEnd();
              }
              struct.setAdditionalIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RecordedSensorData struct)
        throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.sensorId != null) {
        oprot.writeFieldBegin(SENSOR_ID_FIELD_DESC);
        oprot.writeString(struct.sensorId);
        oprot.writeFieldEnd();
      }
      if (struct.measurements != null) {
        oprot.writeFieldBegin(MEASUREMENTS_FIELD_DESC);
        {
          oprot.writeListBegin(
              new org.apache.thrift.protocol.TList(
                  org.apache.thrift.protocol.TType.STRUCT, struct.measurements.size()));
          for (RecordedSensorMeasurement _iter7 : struct.measurements) {
            _iter7.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      if (struct.additional != null) {
        oprot.writeFieldBegin(ADDITIONAL_FIELD_DESC);
        {
          oprot.writeMapBegin(
              new org.apache.thrift.protocol.TMap(
                  org.apache.thrift.protocol.TType.STRING,
                  org.apache.thrift.protocol.TType.STRING,
                  struct.additional.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter8 :
              struct.additional.entrySet()) {
            oprot.writeString(_iter8.getKey());
            oprot.writeString(_iter8.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
  }

  private static class RecordedSensorDataTupleSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RecordedSensorDataTupleScheme getScheme() {
      return new RecordedSensorDataTupleScheme();
    }
  }

  private static class RecordedSensorDataTupleScheme
      extends org.apache.thrift.scheme.TupleScheme<RecordedSensorData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecordedSensorData struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSensorId()) {
        optionals.set(0);
      }
      if (struct.isSetMeasurements()) {
        optionals.set(1);
      }
      if (struct.isSetTimestamp()) {
        optionals.set(2);
      }
      if (struct.isSetAdditional()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetSensorId()) {
        oprot.writeString(struct.sensorId);
      }
      if (struct.isSetMeasurements()) {
        {
          oprot.writeI32(struct.measurements.size());
          for (RecordedSensorMeasurement _iter9 : struct.measurements) {
            _iter9.write(oprot);
          }
        }
      }
      if (struct.isSetTimestamp()) {
        oprot.writeI64(struct.timestamp);
      }
      if (struct.isSetAdditional()) {
        {
          oprot.writeI32(struct.additional.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter10 :
              struct.additional.entrySet()) {
            oprot.writeString(_iter10.getKey());
            oprot.writeString(_iter10.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecordedSensorData struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.sensorId = iprot.readString();
        struct.setSensorIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list11 =
              iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.measurements = new java.util.ArrayList<RecordedSensorMeasurement>(_list11.size);
          @org.apache.thrift.annotation.Nullable RecordedSensorMeasurement _elem12;
          for (int _i13 = 0; _i13 < _list11.size; ++_i13) {
            _elem12 = new RecordedSensorMeasurement();
            _elem12.read(iprot);
            struct.measurements.add(_elem12);
          }
        }
        struct.setMeasurementsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.timestamp = iprot.readI64();
        struct.setTimestampIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map14 =
              iprot.readMapBegin(
                  org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING);
          struct.additional =
              new java.util.HashMap<java.lang.String, java.lang.String>(2 * _map14.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key15;
          @org.apache.thrift.annotation.Nullable java.lang.String _val16;
          for (int _i17 = 0; _i17 < _map14.size; ++_i17) {
            _key15 = iprot.readString();
            _val16 = iprot.readString();
            struct.additional.put(_key15, _val16);
          }
        }
        struct.setAdditionalIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
      org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
            ? STANDARD_SCHEME_FACTORY
            : TUPLE_SCHEME_FACTORY)
        .getScheme();
  }
}
