/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * <p>DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.softwareforce.iotvm.shared.extensions.sensing_recording.spec;

@javax.annotation.Generated(
    value = "Autogenerated by Thrift Compiler (0.18.1)",
    date = "2023-09-02")
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SensingRecordingService {

  /** Defines the sensing recording service contract. */
  public interface Iface extends org.softwareforce.iotvm.shared.extensions.base.BaseService.Iface {

    public void recordSensorData(RecordedSensorData recordedSensorData)
        throws org.apache.thrift.TException;

    public java.util.List<PhysicalQuantityDataPoint> getBasicAggregationsCTFReals(
        java.util.List<java.lang.String> sensorIds,
        java.lang.String physicalQuantity,
        long fromTimestamp,
        long toTimestamp)
        throws org.apache.thrift.TException;
  }

  public interface AsyncIface
      extends org.softwareforce.iotvm.shared.extensions.base.BaseService.AsyncIface {

    public void recordSensorData(
        RecordedSensorData recordedSensorData,
        org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler)
        throws org.apache.thrift.TException;

    public void getBasicAggregationsCTFReals(
        java.util.List<java.lang.String> sensorIds,
        java.lang.String physicalQuantity,
        long fromTimestamp,
        long toTimestamp,
        org.apache.thrift.async.AsyncMethodCallback<java.util.List<PhysicalQuantityDataPoint>>
            resultHandler)
        throws org.apache.thrift.TException;
  }

  public static class Client
      extends org.softwareforce.iotvm.shared.extensions.base.BaseService.Client implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}

      @Override
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }

      @Override
      public Client getClient(
          org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot) {
      super(prot, prot);
    }

    public Client(
        org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    @Override
    public void recordSensorData(RecordedSensorData recordedSensorData)
        throws org.apache.thrift.TException {
      send_recordSensorData(recordedSensorData);
    }

    public void send_recordSensorData(RecordedSensorData recordedSensorData)
        throws org.apache.thrift.TException {
      recordSensorData_args args = new recordSensorData_args();
      args.setRecordedSensorData(recordedSensorData);
      sendBaseOneway("recordSensorData", args);
    }

    @Override
    public java.util.List<PhysicalQuantityDataPoint> getBasicAggregationsCTFReals(
        java.util.List<java.lang.String> sensorIds,
        java.lang.String physicalQuantity,
        long fromTimestamp,
        long toTimestamp)
        throws org.apache.thrift.TException {
      send_getBasicAggregationsCTFReals(sensorIds, physicalQuantity, fromTimestamp, toTimestamp);
      return recv_getBasicAggregationsCTFReals();
    }

    public void send_getBasicAggregationsCTFReals(
        java.util.List<java.lang.String> sensorIds,
        java.lang.String physicalQuantity,
        long fromTimestamp,
        long toTimestamp)
        throws org.apache.thrift.TException {
      getBasicAggregationsCTFReals_args args = new getBasicAggregationsCTFReals_args();
      args.setSensorIds(sensorIds);
      args.setPhysicalQuantity(physicalQuantity);
      args.setFromTimestamp(fromTimestamp);
      args.setToTimestamp(toTimestamp);
      sendBase("getBasicAggregationsCTFReals", args);
    }

    public java.util.List<PhysicalQuantityDataPoint> recv_getBasicAggregationsCTFReals()
        throws org.apache.thrift.TException {
      getBasicAggregationsCTFReals_result result = new getBasicAggregationsCTFReals_result();
      receiveBase(result, "getBasicAggregationsCTFReals");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(
          org.apache.thrift.TApplicationException.MISSING_RESULT,
          "getBasicAggregationsCTFReals failed: unknown result");
    }
  }

  public static class AsyncClient
      extends org.softwareforce.iotvm.shared.extensions.base.BaseService.AsyncClient
      implements AsyncIface {
    public static class Factory
        implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;

      public Factory(
          org.apache.thrift.async.TAsyncClientManager clientManager,
          org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }

      @Override
      public AsyncClient getAsyncClient(
          org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(
        org.apache.thrift.protocol.TProtocolFactory protocolFactory,
        org.apache.thrift.async.TAsyncClientManager clientManager,
        org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    @Override
    public void recordSensorData(
        RecordedSensorData recordedSensorData,
        org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler)
        throws org.apache.thrift.TException {
      checkReady();
      recordSensorData_call method_call =
          new recordSensorData_call(
              recordedSensorData, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class recordSensorData_call
        extends org.apache.thrift.async.TAsyncMethodCall<Void> {
      private RecordedSensorData recordedSensorData;

      public recordSensorData_call(
          RecordedSensorData recordedSensorData,
          org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler,
          org.apache.thrift.async.TAsyncClient client,
          org.apache.thrift.protocol.TProtocolFactory protocolFactory,
          org.apache.thrift.transport.TNonblockingTransport transport)
          throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, true);
        this.recordedSensorData = recordedSensorData;
      }

      @Override
      public void write_args(org.apache.thrift.protocol.TProtocol prot)
          throws org.apache.thrift.TException {
        prot.writeMessageBegin(
            new org.apache.thrift.protocol.TMessage(
                "recordSensorData", org.apache.thrift.protocol.TMessageType.ONEWAY, 0));
        recordSensorData_args args = new recordSensorData_args();
        args.setRecordedSensorData(recordedSensorData);
        args.write(prot);
        prot.writeMessageEnd();
      }

      @Override
      public Void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport =
            new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot =
            client.getProtocolFactory().getProtocol(memoryTransport);
        return null;
      }
    }

    @Override
    public void getBasicAggregationsCTFReals(
        java.util.List<java.lang.String> sensorIds,
        java.lang.String physicalQuantity,
        long fromTimestamp,
        long toTimestamp,
        org.apache.thrift.async.AsyncMethodCallback<java.util.List<PhysicalQuantityDataPoint>>
            resultHandler)
        throws org.apache.thrift.TException {
      checkReady();
      getBasicAggregationsCTFReals_call method_call =
          new getBasicAggregationsCTFReals_call(
              sensorIds,
              physicalQuantity,
              fromTimestamp,
              toTimestamp,
              resultHandler,
              this,
              ___protocolFactory,
              ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getBasicAggregationsCTFReals_call
        extends org.apache.thrift.async.TAsyncMethodCall<
            java.util.List<PhysicalQuantityDataPoint>> {
      private java.util.List<java.lang.String> sensorIds;
      private java.lang.String physicalQuantity;
      private long fromTimestamp;
      private long toTimestamp;

      public getBasicAggregationsCTFReals_call(
          java.util.List<java.lang.String> sensorIds,
          java.lang.String physicalQuantity,
          long fromTimestamp,
          long toTimestamp,
          org.apache.thrift.async.AsyncMethodCallback<java.util.List<PhysicalQuantityDataPoint>>
              resultHandler,
          org.apache.thrift.async.TAsyncClient client,
          org.apache.thrift.protocol.TProtocolFactory protocolFactory,
          org.apache.thrift.transport.TNonblockingTransport transport)
          throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.sensorIds = sensorIds;
        this.physicalQuantity = physicalQuantity;
        this.fromTimestamp = fromTimestamp;
        this.toTimestamp = toTimestamp;
      }

      @Override
      public void write_args(org.apache.thrift.protocol.TProtocol prot)
          throws org.apache.thrift.TException {
        prot.writeMessageBegin(
            new org.apache.thrift.protocol.TMessage(
                "getBasicAggregationsCTFReals", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getBasicAggregationsCTFReals_args args = new getBasicAggregationsCTFReals_args();
        args.setSensorIds(sensorIds);
        args.setPhysicalQuantity(physicalQuantity);
        args.setFromTimestamp(fromTimestamp);
        args.setToTimestamp(toTimestamp);
        args.write(prot);
        prot.writeMessageEnd();
      }

      @Override
      public java.util.List<PhysicalQuantityDataPoint> getResult()
          throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport =
            new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot =
            client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getBasicAggregationsCTFReals();
      }
    }
  }

  public static class Processor<I extends Iface>
      extends org.softwareforce.iotvm.shared.extensions.base.BaseService.Processor<I>
      implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER =
        org.slf4j.LoggerFactory.getLogger(Processor.class.getName());

    public Processor(I iface) {
      super(
          iface,
          getProcessMap(
              new java.util.HashMap<
                  java.lang.String,
                  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(
        I iface,
        java.util.Map<
                java.lang.String,
                org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>
            processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface>
        java.util.Map<
                java.lang.String,
                org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>
            getProcessMap(
                java.util.Map<
                        java.lang.String,
                        org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>
                    processMap) {
      processMap.put("recordSensorData", new recordSensorData());
      processMap.put("getBasicAggregationsCTFReals", new getBasicAggregationsCTFReals());
      return processMap;
    }

    public static class recordSensorData<I extends Iface>
        extends org.apache.thrift.ProcessFunction<I, recordSensorData_args> {
      public recordSensorData() {
        super("recordSensorData");
      }

      @Override
      public recordSensorData_args getEmptyArgsInstance() {
        return new recordSensorData_args();
      }

      @Override
      protected boolean isOneway() {
        return true;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      @Override
      public org.apache.thrift.TBase getResult(I iface, recordSensorData_args args)
          throws org.apache.thrift.TException {
        iface.recordSensorData(args.recordedSensorData);
        return null;
      }
    }

    public static class getBasicAggregationsCTFReals<I extends Iface>
        extends org.apache.thrift.ProcessFunction<I, getBasicAggregationsCTFReals_args> {
      public getBasicAggregationsCTFReals() {
        super("getBasicAggregationsCTFReals");
      }

      @Override
      public getBasicAggregationsCTFReals_args getEmptyArgsInstance() {
        return new getBasicAggregationsCTFReals_args();
      }

      @Override
      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      @Override
      public getBasicAggregationsCTFReals_result getResult(
          I iface, getBasicAggregationsCTFReals_args args) throws org.apache.thrift.TException {
        getBasicAggregationsCTFReals_result result = new getBasicAggregationsCTFReals_result();
        result.success =
            iface.getBasicAggregationsCTFReals(
                args.sensorIds, args.physicalQuantity, args.fromTimestamp, args.toTimestamp);
        return result;
      }
    }
  }

  public static class AsyncProcessor<I extends AsyncIface>
      extends org.softwareforce.iotvm.shared.extensions.base.BaseService.AsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER =
        org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());

    public AsyncProcessor(I iface) {
      super(
          iface,
          getProcessMap(
              new java.util.HashMap<
                  java.lang.String,
                  org.apache.thrift.AsyncProcessFunction<
                      I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(
        I iface,
        java.util.Map<
                java.lang.String,
                org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>
            processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface>
        java.util.Map<
                java.lang.String,
                org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>
            getProcessMap(
                java.util.Map<
                        java.lang.String,
                        org.apache.thrift.AsyncProcessFunction<
                            I, ? extends org.apache.thrift.TBase, ?>>
                    processMap) {
      processMap.put("recordSensorData", new recordSensorData());
      processMap.put("getBasicAggregationsCTFReals", new getBasicAggregationsCTFReals());
      return processMap;
    }

    public static class recordSensorData<I extends AsyncIface>
        extends org.apache.thrift.AsyncProcessFunction<I, recordSensorData_args, Void> {
      public recordSensorData() {
        super("recordSensorData");
      }

      @Override
      public recordSensorData_args getEmptyArgsInstance() {
        return new recordSensorData_args();
      }

      @Override
      public org.apache.thrift.async.AsyncMethodCallback<Void> getResultHandler(
          final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb,
          final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Void>() {
          @Override
          public void onComplete(Void o) {}

          @Override
          public void onError(java.lang.Exception e) {
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
            } else {
              _LOGGER.error("Exception inside oneway handler", e);
            }
          }
        };
      }

      @Override
      protected boolean isOneway() {
        return true;
      }

      @Override
      public void start(
          I iface,
          recordSensorData_args args,
          org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler)
          throws org.apache.thrift.TException {
        iface.recordSensorData(args.recordedSensorData, resultHandler);
      }
    }

    public static class getBasicAggregationsCTFReals<I extends AsyncIface>
        extends org.apache.thrift.AsyncProcessFunction<
            I, getBasicAggregationsCTFReals_args, java.util.List<PhysicalQuantityDataPoint>> {
      public getBasicAggregationsCTFReals() {
        super("getBasicAggregationsCTFReals");
      }

      @Override
      public getBasicAggregationsCTFReals_args getEmptyArgsInstance() {
        return new getBasicAggregationsCTFReals_args();
      }

      @Override
      public org.apache.thrift.async.AsyncMethodCallback<java.util.List<PhysicalQuantityDataPoint>>
          getResultHandler(
              final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb,
              final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<
            java.util.List<PhysicalQuantityDataPoint>>() {
          @Override
          public void onComplete(java.util.List<PhysicalQuantityDataPoint> o) {
            getBasicAggregationsCTFReals_result result = new getBasicAggregationsCTFReals_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY, seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }

          @Override
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            getBasicAggregationsCTFReals_result result = new getBasicAggregationsCTFReals_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException) e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg =
                  new org.apache.thrift.TApplicationException(
                      org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb, msg, msgType, seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      @Override
      protected boolean isOneway() {
        return false;
      }

      @Override
      public void start(
          I iface,
          getBasicAggregationsCTFReals_args args,
          org.apache.thrift.async.AsyncMethodCallback<java.util.List<PhysicalQuantityDataPoint>>
              resultHandler)
          throws org.apache.thrift.TException {
        iface.getBasicAggregationsCTFReals(
            args.sensorIds,
            args.physicalQuantity,
            args.fromTimestamp,
            args.toTimestamp,
            resultHandler);
      }
    }
  }

  @SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
  public static class recordSensorData_args
      implements org.apache.thrift.TBase<recordSensorData_args, recordSensorData_args._Fields>,
          java.io.Serializable,
          Cloneable,
          Comparable<recordSensorData_args> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
        new org.apache.thrift.protocol.TStruct("recordSensorData_args");

    private static final org.apache.thrift.protocol.TField RECORDED_SENSOR_DATA_FIELD_DESC =
        new org.apache.thrift.protocol.TField(
            "recordedSensorData", org.apache.thrift.protocol.TType.STRUCT, (short) 1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
        new recordSensorData_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
        new recordSensorData_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable RecordedSensorData recordedSensorData; // required

    /**
     * The set of fields this struct contains, along with convenience methods for finding and
     * manipulating them.
     */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      RECORDED_SENSOR_DATA((short) 1, "recordedSensorData");

      private static final java.util.Map<java.lang.String, _Fields> byName =
          new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /** Find the _Fields constant that matches fieldId, or null if its not found. */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch (fieldId) {
          case 1: // RECORDED_SENSOR_DATA
            return RECORDED_SENSOR_DATA;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null)
          throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /** Find the _Fields constant that matches name, or null if its not found. */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      @Override
      public short getThriftFieldId() {
        return _thriftId;
      }

      @Override
      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData>
        metaDataMap;

    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
          new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(
          _Fields.RECORDED_SENSOR_DATA,
          new org.apache.thrift.meta_data.FieldMetaData(
              "recordedSensorData",
              org.apache.thrift.TFieldRequirementType.DEFAULT,
              new org.apache.thrift.meta_data.StructMetaData(
                  org.apache.thrift.protocol.TType.STRUCT, RecordedSensorData.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
          recordSensorData_args.class, metaDataMap);
    }

    public recordSensorData_args() {}

    public recordSensorData_args(RecordedSensorData recordedSensorData) {
      this();
      this.recordedSensorData = recordedSensorData;
    }

    /** Performs a deep copy on <i>other</i>. */
    public recordSensorData_args(recordSensorData_args other) {
      if (other.isSetRecordedSensorData()) {
        this.recordedSensorData = new RecordedSensorData(other.recordedSensorData);
      }
    }

    @Override
    public recordSensorData_args deepCopy() {
      return new recordSensorData_args(this);
    }

    @Override
    public void clear() {
      this.recordedSensorData = null;
    }

    @org.apache.thrift.annotation.Nullable
    public RecordedSensorData getRecordedSensorData() {
      return this.recordedSensorData;
    }

    public recordSensorData_args setRecordedSensorData(
        @org.apache.thrift.annotation.Nullable RecordedSensorData recordedSensorData) {
      this.recordedSensorData = recordedSensorData;
      return this;
    }

    public void unsetRecordedSensorData() {
      this.recordedSensorData = null;
    }

    /**
     * Returns true if field recordedSensorData is set (has been assigned a value) and false
     * otherwise
     */
    public boolean isSetRecordedSensorData() {
      return this.recordedSensorData != null;
    }

    public void setRecordedSensorDataIsSet(boolean value) {
      if (!value) {
        this.recordedSensorData = null;
      }
    }

    @Override
    public void setFieldValue(
        _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
        case RECORDED_SENSOR_DATA:
          if (value == null) {
            unsetRecordedSensorData();
          } else {
            setRecordedSensorData((RecordedSensorData) value);
          }
          break;
      }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
        case RECORDED_SENSOR_DATA:
          return getRecordedSensorData();
      }
      throw new java.lang.IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
     * otherwise
     */
    @Override
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
        case RECORDED_SENSOR_DATA:
          return isSetRecordedSensorData();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that instanceof recordSensorData_args) return this.equals((recordSensorData_args) that);
      return false;
    }

    public boolean equals(recordSensorData_args that) {
      if (that == null) return false;
      if (this == that) return true;

      boolean this_present_recordedSensorData = true && this.isSetRecordedSensorData();
      boolean that_present_recordedSensorData = true && that.isSetRecordedSensorData();
      if (this_present_recordedSensorData || that_present_recordedSensorData) {
        if (!(this_present_recordedSensorData && that_present_recordedSensorData)) return false;
        if (!this.recordedSensorData.equals(that.recordedSensorData)) return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetRecordedSensorData()) ? 131071 : 524287);
      if (isSetRecordedSensorData()) hashCode = hashCode * 8191 + recordedSensorData.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(recordSensorData_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison =
          java.lang.Boolean.compare(isSetRecordedSensorData(), other.isSetRecordedSensorData());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRecordedSensorData()) {
        lastComparison =
            org.apache.thrift.TBaseHelper.compareTo(
                this.recordedSensorData, other.recordedSensorData);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
        throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
        throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("recordSensorData_args(");
      boolean first = true;

      sb.append("recordedSensorData:");
      if (this.recordedSensorData == null) {
        sb.append("null");
      } else {
        sb.append(this.recordedSensorData);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (recordedSensorData != null) {
        recordedSensorData.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(
            new org.apache.thrift.protocol.TCompactProtocol(
                new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in)
        throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(
            new org.apache.thrift.protocol.TCompactProtocol(
                new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class recordSensorData_argsStandardSchemeFactory
        implements org.apache.thrift.scheme.SchemeFactory {
      @Override
      public recordSensorData_argsStandardScheme getScheme() {
        return new recordSensorData_argsStandardScheme();
      }
    }

    private static class recordSensorData_argsStandardScheme
        extends org.apache.thrift.scheme.StandardScheme<recordSensorData_args> {

      @Override
      public void read(org.apache.thrift.protocol.TProtocol iprot, recordSensorData_args struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true) {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 1: // RECORDED_SENSOR_DATA
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.recordedSensorData = new RecordedSensorData();
                struct.recordedSensorData.read(iprot);
                struct.setRecordedSensorDataIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate
        // method
        struct.validate();
      }

      @Override
      public void write(org.apache.thrift.protocol.TProtocol oprot, recordSensorData_args struct)
          throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.recordedSensorData != null) {
          oprot.writeFieldBegin(RECORDED_SENSOR_DATA_FIELD_DESC);
          struct.recordedSensorData.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }
    }

    private static class recordSensorData_argsTupleSchemeFactory
        implements org.apache.thrift.scheme.SchemeFactory {
      @Override
      public recordSensorData_argsTupleScheme getScheme() {
        return new recordSensorData_argsTupleScheme();
      }
    }

    private static class recordSensorData_argsTupleScheme
        extends org.apache.thrift.scheme.TupleScheme<recordSensorData_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, recordSensorData_args struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot =
            (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetRecordedSensorData()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetRecordedSensorData()) {
          struct.recordedSensorData.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, recordSensorData_args struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot =
            (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.recordedSensorData = new RecordedSensorData();
          struct.recordedSensorData.read(iprot);
          struct.setRecordedSensorDataIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
        org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
              ? STANDARD_SCHEME_FACTORY
              : TUPLE_SCHEME_FACTORY)
          .getScheme();
    }
  }

  @SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
  public static class getBasicAggregationsCTFReals_args
      implements org.apache.thrift.TBase<
              getBasicAggregationsCTFReals_args, getBasicAggregationsCTFReals_args._Fields>,
          java.io.Serializable,
          Cloneable,
          Comparable<getBasicAggregationsCTFReals_args> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
        new org.apache.thrift.protocol.TStruct("getBasicAggregationsCTFReals_args");

    private static final org.apache.thrift.protocol.TField SENSOR_IDS_FIELD_DESC =
        new org.apache.thrift.protocol.TField(
            "sensorIds", org.apache.thrift.protocol.TType.LIST, (short) 1);
    private static final org.apache.thrift.protocol.TField PHYSICAL_QUANTITY_FIELD_DESC =
        new org.apache.thrift.protocol.TField(
            "physicalQuantity", org.apache.thrift.protocol.TType.STRING, (short) 2);
    private static final org.apache.thrift.protocol.TField FROM_TIMESTAMP_FIELD_DESC =
        new org.apache.thrift.protocol.TField(
            "fromTimestamp", org.apache.thrift.protocol.TType.I64, (short) 3);
    private static final org.apache.thrift.protocol.TField TO_TIMESTAMP_FIELD_DESC =
        new org.apache.thrift.protocol.TField(
            "toTimestamp", org.apache.thrift.protocol.TType.I64, (short) 4);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
        new getBasicAggregationsCTFReals_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
        new getBasicAggregationsCTFReals_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String>
        sensorIds; // required
    public @org.apache.thrift.annotation.Nullable java.lang.String physicalQuantity; // required
    public long fromTimestamp; // required
    public long toTimestamp; // required

    /**
     * The set of fields this struct contains, along with convenience methods for finding and
     * manipulating them.
     */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SENSOR_IDS((short) 1, "sensorIds"),
      PHYSICAL_QUANTITY((short) 2, "physicalQuantity"),
      FROM_TIMESTAMP((short) 3, "fromTimestamp"),
      TO_TIMESTAMP((short) 4, "toTimestamp");

      private static final java.util.Map<java.lang.String, _Fields> byName =
          new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /** Find the _Fields constant that matches fieldId, or null if its not found. */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch (fieldId) {
          case 1: // SENSOR_IDS
            return SENSOR_IDS;
          case 2: // PHYSICAL_QUANTITY
            return PHYSICAL_QUANTITY;
          case 3: // FROM_TIMESTAMP
            return FROM_TIMESTAMP;
          case 4: // TO_TIMESTAMP
            return TO_TIMESTAMP;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null)
          throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /** Find the _Fields constant that matches name, or null if its not found. */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      @Override
      public short getThriftFieldId() {
        return _thriftId;
      }

      @Override
      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __FROMTIMESTAMP_ISSET_ID = 0;
    private static final int __TOTIMESTAMP_ISSET_ID = 1;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData>
        metaDataMap;

    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
          new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(
          _Fields.SENSOR_IDS,
          new org.apache.thrift.meta_data.FieldMetaData(
              "sensorIds",
              org.apache.thrift.TFieldRequirementType.DEFAULT,
              new org.apache.thrift.meta_data.ListMetaData(
                  org.apache.thrift.protocol.TType.LIST,
                  new org.apache.thrift.meta_data.FieldValueMetaData(
                      org.apache.thrift.protocol.TType.STRING))));
      tmpMap.put(
          _Fields.PHYSICAL_QUANTITY,
          new org.apache.thrift.meta_data.FieldMetaData(
              "physicalQuantity",
              org.apache.thrift.TFieldRequirementType.DEFAULT,
              new org.apache.thrift.meta_data.FieldValueMetaData(
                  org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(
          _Fields.FROM_TIMESTAMP,
          new org.apache.thrift.meta_data.FieldMetaData(
              "fromTimestamp",
              org.apache.thrift.TFieldRequirementType.DEFAULT,
              new org.apache.thrift.meta_data.FieldValueMetaData(
                  org.apache.thrift.protocol.TType.I64)));
      tmpMap.put(
          _Fields.TO_TIMESTAMP,
          new org.apache.thrift.meta_data.FieldMetaData(
              "toTimestamp",
              org.apache.thrift.TFieldRequirementType.DEFAULT,
              new org.apache.thrift.meta_data.FieldValueMetaData(
                  org.apache.thrift.protocol.TType.I64)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
          getBasicAggregationsCTFReals_args.class, metaDataMap);
    }

    public getBasicAggregationsCTFReals_args() {}

    public getBasicAggregationsCTFReals_args(
        java.util.List<java.lang.String> sensorIds,
        java.lang.String physicalQuantity,
        long fromTimestamp,
        long toTimestamp) {
      this();
      this.sensorIds = sensorIds;
      this.physicalQuantity = physicalQuantity;
      this.fromTimestamp = fromTimestamp;
      setFromTimestampIsSet(true);
      this.toTimestamp = toTimestamp;
      setToTimestampIsSet(true);
    }

    /** Performs a deep copy on <i>other</i>. */
    public getBasicAggregationsCTFReals_args(getBasicAggregationsCTFReals_args other) {
      __isset_bitfield = other.__isset_bitfield;
      if (other.isSetSensorIds()) {
        java.util.List<java.lang.String> __this__sensorIds =
            new java.util.ArrayList<java.lang.String>(other.sensorIds);
        this.sensorIds = __this__sensorIds;
      }
      if (other.isSetPhysicalQuantity()) {
        this.physicalQuantity = other.physicalQuantity;
      }
      this.fromTimestamp = other.fromTimestamp;
      this.toTimestamp = other.toTimestamp;
    }

    @Override
    public getBasicAggregationsCTFReals_args deepCopy() {
      return new getBasicAggregationsCTFReals_args(this);
    }

    @Override
    public void clear() {
      this.sensorIds = null;
      this.physicalQuantity = null;
      setFromTimestampIsSet(false);
      this.fromTimestamp = 0;
      setToTimestampIsSet(false);
      this.toTimestamp = 0;
    }

    public int getSensorIdsSize() {
      return (this.sensorIds == null) ? 0 : this.sensorIds.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<java.lang.String> getSensorIdsIterator() {
      return (this.sensorIds == null) ? null : this.sensorIds.iterator();
    }

    public void addToSensorIds(java.lang.String elem) {
      if (this.sensorIds == null) {
        this.sensorIds = new java.util.ArrayList<java.lang.String>();
      }
      this.sensorIds.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<java.lang.String> getSensorIds() {
      return this.sensorIds;
    }

    public getBasicAggregationsCTFReals_args setSensorIds(
        @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> sensorIds) {
      this.sensorIds = sensorIds;
      return this;
    }

    public void unsetSensorIds() {
      this.sensorIds = null;
    }

    /** Returns true if field sensorIds is set (has been assigned a value) and false otherwise */
    public boolean isSetSensorIds() {
      return this.sensorIds != null;
    }

    public void setSensorIdsIsSet(boolean value) {
      if (!value) {
        this.sensorIds = null;
      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getPhysicalQuantity() {
      return this.physicalQuantity;
    }

    public getBasicAggregationsCTFReals_args setPhysicalQuantity(
        @org.apache.thrift.annotation.Nullable java.lang.String physicalQuantity) {
      this.physicalQuantity = physicalQuantity;
      return this;
    }

    public void unsetPhysicalQuantity() {
      this.physicalQuantity = null;
    }

    /**
     * Returns true if field physicalQuantity is set (has been assigned a value) and false otherwise
     */
    public boolean isSetPhysicalQuantity() {
      return this.physicalQuantity != null;
    }

    public void setPhysicalQuantityIsSet(boolean value) {
      if (!value) {
        this.physicalQuantity = null;
      }
    }

    public long getFromTimestamp() {
      return this.fromTimestamp;
    }

    public getBasicAggregationsCTFReals_args setFromTimestamp(long fromTimestamp) {
      this.fromTimestamp = fromTimestamp;
      setFromTimestampIsSet(true);
      return this;
    }

    public void unsetFromTimestamp() {
      __isset_bitfield =
          org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FROMTIMESTAMP_ISSET_ID);
    }

    /**
     * Returns true if field fromTimestamp is set (has been assigned a value) and false otherwise
     */
    public boolean isSetFromTimestamp() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FROMTIMESTAMP_ISSET_ID);
    }

    public void setFromTimestampIsSet(boolean value) {
      __isset_bitfield =
          org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FROMTIMESTAMP_ISSET_ID, value);
    }

    public long getToTimestamp() {
      return this.toTimestamp;
    }

    public getBasicAggregationsCTFReals_args setToTimestamp(long toTimestamp) {
      this.toTimestamp = toTimestamp;
      setToTimestampIsSet(true);
      return this;
    }

    public void unsetToTimestamp() {
      __isset_bitfield =
          org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOTIMESTAMP_ISSET_ID);
    }

    /** Returns true if field toTimestamp is set (has been assigned a value) and false otherwise */
    public boolean isSetToTimestamp() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOTIMESTAMP_ISSET_ID);
    }

    public void setToTimestampIsSet(boolean value) {
      __isset_bitfield =
          org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOTIMESTAMP_ISSET_ID, value);
    }

    @Override
    public void setFieldValue(
        _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
        case SENSOR_IDS:
          if (value == null) {
            unsetSensorIds();
          } else {
            setSensorIds((java.util.List<java.lang.String>) value);
          }
          break;

        case PHYSICAL_QUANTITY:
          if (value == null) {
            unsetPhysicalQuantity();
          } else {
            setPhysicalQuantity((java.lang.String) value);
          }
          break;

        case FROM_TIMESTAMP:
          if (value == null) {
            unsetFromTimestamp();
          } else {
            setFromTimestamp((java.lang.Long) value);
          }
          break;

        case TO_TIMESTAMP:
          if (value == null) {
            unsetToTimestamp();
          } else {
            setToTimestamp((java.lang.Long) value);
          }
          break;
      }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
        case SENSOR_IDS:
          return getSensorIds();

        case PHYSICAL_QUANTITY:
          return getPhysicalQuantity();

        case FROM_TIMESTAMP:
          return getFromTimestamp();

        case TO_TIMESTAMP:
          return getToTimestamp();
      }
      throw new java.lang.IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
     * otherwise
     */
    @Override
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
        case SENSOR_IDS:
          return isSetSensorIds();
        case PHYSICAL_QUANTITY:
          return isSetPhysicalQuantity();
        case FROM_TIMESTAMP:
          return isSetFromTimestamp();
        case TO_TIMESTAMP:
          return isSetToTimestamp();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that instanceof getBasicAggregationsCTFReals_args)
        return this.equals((getBasicAggregationsCTFReals_args) that);
      return false;
    }

    public boolean equals(getBasicAggregationsCTFReals_args that) {
      if (that == null) return false;
      if (this == that) return true;

      boolean this_present_sensorIds = true && this.isSetSensorIds();
      boolean that_present_sensorIds = true && that.isSetSensorIds();
      if (this_present_sensorIds || that_present_sensorIds) {
        if (!(this_present_sensorIds && that_present_sensorIds)) return false;
        if (!this.sensorIds.equals(that.sensorIds)) return false;
      }

      boolean this_present_physicalQuantity = true && this.isSetPhysicalQuantity();
      boolean that_present_physicalQuantity = true && that.isSetPhysicalQuantity();
      if (this_present_physicalQuantity || that_present_physicalQuantity) {
        if (!(this_present_physicalQuantity && that_present_physicalQuantity)) return false;
        if (!this.physicalQuantity.equals(that.physicalQuantity)) return false;
      }

      boolean this_present_fromTimestamp = true;
      boolean that_present_fromTimestamp = true;
      if (this_present_fromTimestamp || that_present_fromTimestamp) {
        if (!(this_present_fromTimestamp && that_present_fromTimestamp)) return false;
        if (this.fromTimestamp != that.fromTimestamp) return false;
      }

      boolean this_present_toTimestamp = true;
      boolean that_present_toTimestamp = true;
      if (this_present_toTimestamp || that_present_toTimestamp) {
        if (!(this_present_toTimestamp && that_present_toTimestamp)) return false;
        if (this.toTimestamp != that.toTimestamp) return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSensorIds()) ? 131071 : 524287);
      if (isSetSensorIds()) hashCode = hashCode * 8191 + sensorIds.hashCode();

      hashCode = hashCode * 8191 + ((isSetPhysicalQuantity()) ? 131071 : 524287);
      if (isSetPhysicalQuantity()) hashCode = hashCode * 8191 + physicalQuantity.hashCode();

      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(fromTimestamp);

      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(toTimestamp);

      return hashCode;
    }

    @Override
    public int compareTo(getBasicAggregationsCTFReals_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.compare(isSetSensorIds(), other.isSetSensorIds());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSensorIds()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sensorIds, other.sensorIds);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison =
          java.lang.Boolean.compare(isSetPhysicalQuantity(), other.isSetPhysicalQuantity());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetPhysicalQuantity()) {
        lastComparison =
            org.apache.thrift.TBaseHelper.compareTo(this.physicalQuantity, other.physicalQuantity);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.compare(isSetFromTimestamp(), other.isSetFromTimestamp());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetFromTimestamp()) {
        lastComparison =
            org.apache.thrift.TBaseHelper.compareTo(this.fromTimestamp, other.fromTimestamp);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.compare(isSetToTimestamp(), other.isSetToTimestamp());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetToTimestamp()) {
        lastComparison =
            org.apache.thrift.TBaseHelper.compareTo(this.toTimestamp, other.toTimestamp);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
        throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
        throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb =
          new java.lang.StringBuilder("getBasicAggregationsCTFReals_args(");
      boolean first = true;

      sb.append("sensorIds:");
      if (this.sensorIds == null) {
        sb.append("null");
      } else {
        sb.append(this.sensorIds);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("physicalQuantity:");
      if (this.physicalQuantity == null) {
        sb.append("null");
      } else {
        sb.append(this.physicalQuantity);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("fromTimestamp:");
      sb.append(this.fromTimestamp);
      first = false;
      if (!first) sb.append(", ");
      sb.append("toTimestamp:");
      sb.append(this.toTimestamp);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(
            new org.apache.thrift.protocol.TCompactProtocol(
                new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in)
        throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and
        // doesn't call the default constructor.
        __isset_bitfield = 0;
        read(
            new org.apache.thrift.protocol.TCompactProtocol(
                new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getBasicAggregationsCTFReals_argsStandardSchemeFactory
        implements org.apache.thrift.scheme.SchemeFactory {
      @Override
      public getBasicAggregationsCTFReals_argsStandardScheme getScheme() {
        return new getBasicAggregationsCTFReals_argsStandardScheme();
      }
    }

    private static class getBasicAggregationsCTFReals_argsStandardScheme
        extends org.apache.thrift.scheme.StandardScheme<getBasicAggregationsCTFReals_args> {

      @Override
      public void read(
          org.apache.thrift.protocol.TProtocol iprot, getBasicAggregationsCTFReals_args struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true) {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 1: // SENSOR_IDS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list18 = iprot.readListBegin();
                  struct.sensorIds = new java.util.ArrayList<java.lang.String>(_list18.size);
                  @org.apache.thrift.annotation.Nullable java.lang.String _elem19;
                  for (int _i20 = 0; _i20 < _list18.size; ++_i20) {
                    _elem19 = iprot.readString();
                    struct.sensorIds.add(_elem19);
                  }
                  iprot.readListEnd();
                }
                struct.setSensorIdsIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // PHYSICAL_QUANTITY
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.physicalQuantity = iprot.readString();
                struct.setPhysicalQuantityIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // FROM_TIMESTAMP
              if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
                struct.fromTimestamp = iprot.readI64();
                struct.setFromTimestampIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 4: // TO_TIMESTAMP
              if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
                struct.toTimestamp = iprot.readI64();
                struct.setToTimestampIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate
        // method
        struct.validate();
      }

      @Override
      public void write(
          org.apache.thrift.protocol.TProtocol oprot, getBasicAggregationsCTFReals_args struct)
          throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.sensorIds != null) {
          oprot.writeFieldBegin(SENSOR_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(
                new org.apache.thrift.protocol.TList(
                    org.apache.thrift.protocol.TType.STRING, struct.sensorIds.size()));
            for (java.lang.String _iter21 : struct.sensorIds) {
              oprot.writeString(_iter21);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        if (struct.physicalQuantity != null) {
          oprot.writeFieldBegin(PHYSICAL_QUANTITY_FIELD_DESC);
          oprot.writeString(struct.physicalQuantity);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(FROM_TIMESTAMP_FIELD_DESC);
        oprot.writeI64(struct.fromTimestamp);
        oprot.writeFieldEnd();
        oprot.writeFieldBegin(TO_TIMESTAMP_FIELD_DESC);
        oprot.writeI64(struct.toTimestamp);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }
    }

    private static class getBasicAggregationsCTFReals_argsTupleSchemeFactory
        implements org.apache.thrift.scheme.SchemeFactory {
      @Override
      public getBasicAggregationsCTFReals_argsTupleScheme getScheme() {
        return new getBasicAggregationsCTFReals_argsTupleScheme();
      }
    }

    private static class getBasicAggregationsCTFReals_argsTupleScheme
        extends org.apache.thrift.scheme.TupleScheme<getBasicAggregationsCTFReals_args> {

      @Override
      public void write(
          org.apache.thrift.protocol.TProtocol prot, getBasicAggregationsCTFReals_args struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot =
            (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSensorIds()) {
          optionals.set(0);
        }
        if (struct.isSetPhysicalQuantity()) {
          optionals.set(1);
        }
        if (struct.isSetFromTimestamp()) {
          optionals.set(2);
        }
        if (struct.isSetToTimestamp()) {
          optionals.set(3);
        }
        oprot.writeBitSet(optionals, 4);
        if (struct.isSetSensorIds()) {
          {
            oprot.writeI32(struct.sensorIds.size());
            for (java.lang.String _iter22 : struct.sensorIds) {
              oprot.writeString(_iter22);
            }
          }
        }
        if (struct.isSetPhysicalQuantity()) {
          oprot.writeString(struct.physicalQuantity);
        }
        if (struct.isSetFromTimestamp()) {
          oprot.writeI64(struct.fromTimestamp);
        }
        if (struct.isSetToTimestamp()) {
          oprot.writeI64(struct.toTimestamp);
        }
      }

      @Override
      public void read(
          org.apache.thrift.protocol.TProtocol prot, getBasicAggregationsCTFReals_args struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot =
            (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(4);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list23 =
                iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
            struct.sensorIds = new java.util.ArrayList<java.lang.String>(_list23.size);
            @org.apache.thrift.annotation.Nullable java.lang.String _elem24;
            for (int _i25 = 0; _i25 < _list23.size; ++_i25) {
              _elem24 = iprot.readString();
              struct.sensorIds.add(_elem24);
            }
          }
          struct.setSensorIdsIsSet(true);
        }
        if (incoming.get(1)) {
          struct.physicalQuantity = iprot.readString();
          struct.setPhysicalQuantityIsSet(true);
        }
        if (incoming.get(2)) {
          struct.fromTimestamp = iprot.readI64();
          struct.setFromTimestampIsSet(true);
        }
        if (incoming.get(3)) {
          struct.toTimestamp = iprot.readI64();
          struct.setToTimestampIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
        org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
              ? STANDARD_SCHEME_FACTORY
              : TUPLE_SCHEME_FACTORY)
          .getScheme();
    }
  }

  @SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
  public static class getBasicAggregationsCTFReals_result
      implements org.apache.thrift.TBase<
              getBasicAggregationsCTFReals_result, getBasicAggregationsCTFReals_result._Fields>,
          java.io.Serializable,
          Cloneable,
          Comparable<getBasicAggregationsCTFReals_result> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
        new org.apache.thrift.protocol.TStruct("getBasicAggregationsCTFReals_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC =
        new org.apache.thrift.protocol.TField(
            "success", org.apache.thrift.protocol.TType.LIST, (short) 0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
        new getBasicAggregationsCTFReals_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
        new getBasicAggregationsCTFReals_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.util.List<PhysicalQuantityDataPoint>
        success; // required

    /**
     * The set of fields this struct contains, along with convenience methods for finding and
     * manipulating them.
     */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short) 0, "success");

      private static final java.util.Map<java.lang.String, _Fields> byName =
          new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /** Find the _Fields constant that matches fieldId, or null if its not found. */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch (fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null)
          throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /** Find the _Fields constant that matches name, or null if its not found. */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      @Override
      public short getThriftFieldId() {
        return _thriftId;
      }

      @Override
      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData>
        metaDataMap;

    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
          new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(
          _Fields.SUCCESS,
          new org.apache.thrift.meta_data.FieldMetaData(
              "success",
              org.apache.thrift.TFieldRequirementType.DEFAULT,
              new org.apache.thrift.meta_data.ListMetaData(
                  org.apache.thrift.protocol.TType.LIST,
                  new org.apache.thrift.meta_data.StructMetaData(
                      org.apache.thrift.protocol.TType.STRUCT, PhysicalQuantityDataPoint.class))));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
          getBasicAggregationsCTFReals_result.class, metaDataMap);
    }

    public getBasicAggregationsCTFReals_result() {}

    public getBasicAggregationsCTFReals_result(java.util.List<PhysicalQuantityDataPoint> success) {
      this();
      this.success = success;
    }

    /** Performs a deep copy on <i>other</i>. */
    public getBasicAggregationsCTFReals_result(getBasicAggregationsCTFReals_result other) {
      if (other.isSetSuccess()) {
        java.util.List<PhysicalQuantityDataPoint> __this__success =
            new java.util.ArrayList<PhysicalQuantityDataPoint>(other.success.size());
        for (PhysicalQuantityDataPoint other_element : other.success) {
          __this__success.add(new PhysicalQuantityDataPoint(other_element));
        }
        this.success = __this__success;
      }
    }

    @Override
    public getBasicAggregationsCTFReals_result deepCopy() {
      return new getBasicAggregationsCTFReals_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<PhysicalQuantityDataPoint> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(PhysicalQuantityDataPoint elem) {
      if (this.success == null) {
        this.success = new java.util.ArrayList<PhysicalQuantityDataPoint>();
      }
      this.success.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<PhysicalQuantityDataPoint> getSuccess() {
      return this.success;
    }

    public getBasicAggregationsCTFReals_result setSuccess(
        @org.apache.thrift.annotation.Nullable java.util.List<PhysicalQuantityDataPoint> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    @Override
    public void setFieldValue(
        _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
        case SUCCESS:
          if (value == null) {
            unsetSuccess();
          } else {
            setSuccess((java.util.List<PhysicalQuantityDataPoint>) value);
          }
          break;
      }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
        case SUCCESS:
          return getSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
     * otherwise
     */
    @Override
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
        case SUCCESS:
          return isSetSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that instanceof getBasicAggregationsCTFReals_result)
        return this.equals((getBasicAggregationsCTFReals_result) that);
      return false;
    }

    public boolean equals(getBasicAggregationsCTFReals_result that) {
      if (that == null) return false;
      if (this == that) return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success)) return false;
        if (!this.success.equals(that.success)) return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess()) hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(getBasicAggregationsCTFReals_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.compare(isSetSuccess(), other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
        throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot)
        throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb =
          new java.lang.StringBuilder("getBasicAggregationsCTFReals_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(
            new org.apache.thrift.protocol.TCompactProtocol(
                new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in)
        throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(
            new org.apache.thrift.protocol.TCompactProtocol(
                new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getBasicAggregationsCTFReals_resultStandardSchemeFactory
        implements org.apache.thrift.scheme.SchemeFactory {
      @Override
      public getBasicAggregationsCTFReals_resultStandardScheme getScheme() {
        return new getBasicAggregationsCTFReals_resultStandardScheme();
      }
    }

    private static class getBasicAggregationsCTFReals_resultStandardScheme
        extends org.apache.thrift.scheme.StandardScheme<getBasicAggregationsCTFReals_result> {

      @Override
      public void read(
          org.apache.thrift.protocol.TProtocol iprot, getBasicAggregationsCTFReals_result struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true) {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list26 = iprot.readListBegin();
                  struct.success = new java.util.ArrayList<PhysicalQuantityDataPoint>(_list26.size);
                  @org.apache.thrift.annotation.Nullable PhysicalQuantityDataPoint _elem27;
                  for (int _i28 = 0; _i28 < _list26.size; ++_i28) {
                    _elem27 = new PhysicalQuantityDataPoint();
                    _elem27.read(iprot);
                    struct.success.add(_elem27);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate
        // method
        struct.validate();
      }

      @Override
      public void write(
          org.apache.thrift.protocol.TProtocol oprot, getBasicAggregationsCTFReals_result struct)
          throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(
                new org.apache.thrift.protocol.TList(
                    org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (PhysicalQuantityDataPoint _iter29 : struct.success) {
              _iter29.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }
    }

    private static class getBasicAggregationsCTFReals_resultTupleSchemeFactory
        implements org.apache.thrift.scheme.SchemeFactory {
      @Override
      public getBasicAggregationsCTFReals_resultTupleScheme getScheme() {
        return new getBasicAggregationsCTFReals_resultTupleScheme();
      }
    }

    private static class getBasicAggregationsCTFReals_resultTupleScheme
        extends org.apache.thrift.scheme.TupleScheme<getBasicAggregationsCTFReals_result> {

      @Override
      public void write(
          org.apache.thrift.protocol.TProtocol prot, getBasicAggregationsCTFReals_result struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot =
            (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (PhysicalQuantityDataPoint _iter30 : struct.success) {
              _iter30.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(
          org.apache.thrift.protocol.TProtocol prot, getBasicAggregationsCTFReals_result struct)
          throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot =
            (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list31 =
                iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.success = new java.util.ArrayList<PhysicalQuantityDataPoint>(_list31.size);
            @org.apache.thrift.annotation.Nullable PhysicalQuantityDataPoint _elem32;
            for (int _i33 = 0; _i33 < _list31.size; ++_i33) {
              _elem32 = new PhysicalQuantityDataPoint();
              _elem32.read(iprot);
              struct.success.add(_elem32);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
        org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
              ? STANDARD_SCHEME_FACTORY
              : TUPLE_SCHEME_FACTORY)
          .getScheme();
    }
  }
}
